### ISSUE TITLE
preact debug mode with ES6 imports

### ISSUE THREAD

**Issue by damianobarbati** [preactjs/preact#1746] opened 2019-06-30 11:53 UTC
The docs are showing `require` usage but what's the correct way to import this with ES6 and only in development?

The following is indeed not working: proptypes validation is enabled after components are mounted thus those are not validated.
```
if (module.hot) {
    module.hot.accept();
    import('preact/debug');
}
```

The following on top of index.js mean including also in production the debug logic.
```
import 'preact/debug'; //eslint-disable-line
```

Any help? 
My hint: `preact/debug` should export a function, this allows the developer to import it and run it only if NODE_ENV=development and tree-shake it away in production.

PS: great work guys!

**Comment by sventschui** [comment] 2019-06-30 20:51
The problem about es6 imports in this case is that they are static. One might not make them conditionally by design. The dynamic import you mentioned makes this possible, but adds the preact options too late and thus some things might not work.

As far as I know there should not be any drawback on using a `require` beneath other es6 imports. When using `if (process.env.NODE_ENV==='development') { require('preact/debug'); }` the statement will be dead-code-eliminated during uglify and thus not end up in your prod bundle at all. Is there any particular reason why you'd want it to be es6?

If you really want this and you are using webpack you could use the [`null-loader`](https://github.com/webpack-contrib/null-loader) for your production build

**Comment by jeremy-coleman** [comment] 2019-07-05 14:57
That syntax isnt es6 import, its dynamic import whose sole purpose is to delay loading

**Comment by marvinhagemeister** [comment] 2019-07-07 12:09
Closing, can't explain it better than @sventschui and @jeremy-coleman did :+1:

**Closed by marvinhagemeister** 2019-07-07 12:09 UTC

**Comment by damianobarbati** [comment] 2019-07-14 10:48
I understand, but can't `preact/debug` handle the logic just as `prop-types` does? Relieving the developer from manually doing that?

https://github.com/facebook/prop-types/blob/master/index.js#L8
