### ISSUE TITLE
Bundle issue with esbuild 0.14.51, 0.14.50 works

### ISSUE THREAD

**Issue by deleonio** [preactjs/preact#3641] opened 2022-07-31 03:12 UTC
- [x] Check if updating to the latest Preact version resolves the issue

**Describe the bug**

Webpack build break.

<img width="527" alt="image" src="https://user-images.githubusercontent.com/6279703/182008247-69d7b6cc-20b6-43d0-a96c-1c22fdf40d06.png">

**To Reproduce**

- https://github.com/deleonio/eslint-preact-issue
- `pnpm i` or `npm i`
- `npm start` -> `BREAK`
- change `esbuild` version in `package.json` to fix version "`0.14.50`"
- `pnpm update` or `npm update`
- `npm start` -> `WORKS`

If possible, please provide a CodeSandbox/Codepen that demonstrates the issue. You can use the following template: https://codesandbox.io/s/preact-x-preact-cli-3-starter-vj285y2rn3

3. See error

**Expected behavior**
What should have happened when following the steps above?

**Comment by deleonio** [comment] 2022-07-31 03:17
https://github.com/evanw/esbuild/issues/2425

**Comment by evanw** [comment] 2022-07-31 03:33
I assume the problem is here:

https://github.com/deleonio/eslint-preact-issue/blob/e6c95e46e629aa5a28abcd39b90f313812ac3686/tsconfig.json#L24

You have told esbuild to preserve JSX in the output, so that's what it's doing. However, this means the output will no longer be valid JavaScript.

**Comment by marvinhagemeister** [comment] 2022-07-31 07:55
Closing as it's not an issue with Preact but with the custom build configuration used here. Like @evanw said, esbuild respects teh `"jsx": "preserve"` option in `tsconfig.json` and JSX is not valid JavaScript.

**Closed by marvinhagemeister** 2022-07-31 07:55 UTC

**Comment by deleonio** [comment] 2022-07-31 13:17
Thank you @evanw and @marvinhagemeister!
