### ISSUE TITLE
node_modules/preact/compat/server.mjs Module not found: Error: Can't resolve 'preact-render-to-string' in 

### ISSUE THREAD

**Issue by rahulbhadhoriya** [preactjs/preact#3095] opened 2021-03-31 17:55 UTC
after version 10.5.13 i am getting this error while building

ERROR in ./node_modules/preact/compat/server.mjs
Module not found: Error: Can't resolve 'preact-render-to-string' in '/Users/B0216312/Desktop/node_modules/preact/compat'
 @ ./node_modules/preact/compat/server.mjs 1:0-4:33 1:0-4:33 1:0-4:33
 @ ./node_modules/google-maps-react/dist/components/InfoWindow.js
 @ ./node_modules/google-maps-react/dist/index.js
 @ ./app/modules/homes/pages/broadband/feasibility/Map.js
 @ ./app/modules/homes/pages/broadband/feasibility/FeasibilitySmart.js
 @ ./app/modules/homes/pages/broadband/feasibility/FeasibilityMain.js
 @ ./app/modules/homes/pages/broadband/home-page/HomePage.js
 @ ./app/modules/homes/lazy.js
 @ ./app/modules/homes/routes.js
 @ ./app/modules/homes/App.js
 @ ./app/modules/homes/common/containers/Root.js
 @ ./app/modules/homes/index.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0 (webpack)/hot/dev-server.js @babel/polyfill ./app/modules/homes/index.js

_Originally posted by @rahulbhadhoriya in https://github.com/preactjs/preact/issues/3061#issuecomment-811289446_

**Comment by rahulbhadhoriya** [comment] 2021-03-31 17:55
downgrading to 10.5.12 works fine.

**Comment by JoviDeCroock** [comment] 2021-04-21 11:12
Hmm I wonder if this is caused by `preact/compat` not having the `preact-render-to-string` dependency.

**Comment by developit** [comment] 2021-04-27 02:32
Possibly, yeah. Maybe the upgrade switched his build to use MJS and that caused the import to fail instead of returning `undefined`?

**Comment by dross15** [comment] 2021-09-10 22:25
@JoviDeCroock is there any update on this? I am trying to upgrade to Next11, using `next-plugin-preact` but also encountering this error when running `yarn build`. I tried downgrading to 10.5.12 but did not have any luck.

**Comment by JoviDeCroock** [comment] 2022-06-17 20:27
@dross15 this has been fixed in the newer versions of next-plugin-preact and `@preact/compat`

**Closed** 2022-10-15 12:35 UTC
