### ISSUE TITLE
Web component's present attributes should be truthy

### ISSUE THREAD

**Issue by yoyomo** [preactjs/preact#4518] opened 2024-09-30 10:14 UTC
- [x] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
When I include a boolean attribute in a web component I expect it to be considered true, much like react does. For example, `<my-web-component truthy-attribute ></my-web-component>` , but instead I must always include a value `truthy-attribute=true` . 

Note: I was looking into `diff/props` and I thought to open a pull request to handle undefined alongside null but had no way of trying it locally so not sure if it would have worked

**Comment by JoviDeCroock** [comment] 2024-10-01 09:03
This issue seemingly lacks a bit of context 😅 we ask for a reproduction for a reason, either provide us with a failing test in our test-suite (which is also a way to test your changes btw) or a stackblitz  reproduction. When I write a test in our test-suite that renders `<my-component the-truth />` I correctly see this translated to `<my-component the-truth='true' />` in the DOM. Not sure what different behavior your are expecting here as the issue isn't describing that.

To make this actionable we'll need to get a reproduction with the actual/expected behavior defined, then we can have a conversation about expectations.

**Comment by rschristian** [comment] 2024-10-08 02:44
Going to close this on out as we don't have enough information to go on.

As mentioned, here's a simple example of this working with `render` & `renderToString`:

```js
import { render } from 'preact';
import { renderToString } from 'preact-render-to-string';

function App() {
	return <web-component truthy-attribute></my-web-component>;
}

render(<App />, document.getElementById('app')); // <web-component truthy-attribute="true"></web-component>
console.log(renderToString(<App />)); // <web-component truthy-attribute></web-component>
```

[REPL](https://preactjs.com/repl?code=aW1wb3J0IHsgcmVuZGVyIH0gZnJvbSAncHJlYWN0JzsKaW1wb3J0IHsgcmVuZGVyVG9TdHJpbmcgfSBmcm9tICdwcmVhY3QtcmVuZGVyLXRvLXN0cmluZyc7CgpmdW5jdGlvbiBBcHAoKSB7CglyZXR1cm4gPHdlYi1jb21wb25lbnQgdHJ1dGh5LWF0dHJpYnV0ZT48L215LXdlYi1jb21wb25lbnQ%2BOwp9CgpyZW5kZXIoPEFwcCAvPiwgZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ2FwcCcpKTsgLy8gPHdlYi1jb21wb25lbnQgdHJ1dGh5LWF0dHJpYnV0ZT0idHJ1ZSI%2BPC93ZWItY29tcG9uZW50Pgpjb25zb2xlLmxvZyhyZW5kZXJUb1N0cmluZyg8QXBwIC8%2BKSk7IC8vIDx3ZWItY29tcG9uZW50IHRydXRoeS1hdHRyaWJ1dGU%2BPC93ZWItY29tcG9uZW50Pg%3D%3D)

Always happy to reopen if you can point us in the right direction.

**Closed by rschristian** 2024-10-08 02:44 UTC
Labels: needs-more-info
