### ISSUE TITLE
useId cannot found in preact@10.10.2

### ISSUE THREAD

**Issue by Aloento** [preactjs/preact#3664] opened 2022-08-11 20:39 UTC
- [ ] Check if updating to the latest Preact version resolves the issue

**Describe the bug**

```
X [ERROR] No matching export in "node_modules/.pnpm/preact@10.10.2/node_modules/preact/compat/dist/compat.module.js" for import "useId"

    node_modules/.pnpm/framer-motion@7.1.0/node_modules/framer-motion/dist/es/components/AnimatePresence/use-presence.mjs:1:21:
      1 │ import { useContext, useId, useEffect } from 'react';
        ╵                      ~~~~~

X [ERROR] No matching export in "node_modules/.pnpm/preact@10.10.2/node_modules/preact/compat/dist/compat.module.js" for import "useId"

    node_modules/.pnpm/framer-motion@7.1.0/node_modules/framer-motion/dist/es/components/AnimatePresence/PresenceChild.mjs:3:9:
      3 │ import { useId, useMemo } from 'react';
        ╵          ~~~~~
```

**Comment by rschristian** [comment] 2022-08-12 00:08
Duplicate of #3373

Preact does not yet provide `useId`, but the current status of implementation can be found here: https://github.com/preactjs/preact/issues/3373#issuecomment-1173779917

**Comment by marvinhagemeister** [comment] 2022-08-12 06:34
Closing because it's already tracked in #3373.

**Closed by marvinhagemeister** 2022-08-12 06:34 UTC
