### ISSUE TITLE
Order still changes when using conditional elements

### ISSUE THREAD

**Issue by mzealey** [preactjs/preact#1982] opened 2019-10-07 09:24 UTC
using latest 10.0.0 full release I am still seeing some issues similar to #1879. Elements are not dropping, but when having a mix of elements where some are conditional and some are not, the order is changing so that conditional elements go to the end or move forward by 1 - I'm not sure which.

Specifically I don't believe that my issue raised in https://github.com/preactjs/preact/pull/1879#issuecomment-531472316 was ever addressed.

**Comment by JoviDeCroock** [comment] 2019-10-07 09:50
Hey @mzealey 

Thanks for the issue report but I think your issue description lacks some information. You are talking about conditional elements and linking issues related to `shouldComponentUpdate`. Are there any specific scenario's where you are running into this issue? Could you offer us a way to reproduce this?

Thanks in advance

**Comment by mzealey** [comment] 2019-10-11 09:16
OK I've finally tracked this down to an issue with PureComponent and <Fragment>... See resaonably minimal case at https://codesandbox.io/s/issue-1982-f1sbl . Order should be 1, 2 but is reversed when PureComponent is used.

**Comment by mzealey** [comment] 2019-10-11 09:19
Sorry didn't save for some reason please refresh, code is:

```
import { hydrate, Fragment } from "preact";
import { PureComponent } from "preact/compat";

class Null extends PureComponent {
  render() {
    return null;
  }
}
class Foo extends PureComponent {
  render() {
    return (
      <Fragment>
        <div>2</div>
      </Fragment>
    );
  }
}
class App extends PureComponent {
  componentDidMount() {
    setTimeout(() => this.setState({ v: 1 }), 500);
  }
  render() {
    return (
      <div>
        <Null />

        {this.state.v && <div>1</div>}

        <Foo />
      </div>
    );
  }
}

hydrate(<App />, window.root);
```

**Comment by marvinhagemeister** [comment] 2019-10-11 09:21
The sandbox works for me, and the issue is reproducible there👍

**Comment by JoviDeCroock** [comment] 2019-10-11 09:26
Oh, this issue should be fixed on master 👍

**Comment by mzealey** [comment] 2019-10-11 12:36
Ya master looks to have fixed this bug.

**Comment by marvinhagemeister** [comment] 2019-10-13 22:33
Closing as the OP confirmed that the issue is not present on `master` we'll cut a patch release soon.

**Closed by marvinhagemeister** 2019-10-13 22:33 UTC
Labels: bug
