### ISSUE TITLE
Polyfilling pointer-events

### ISSUE THREAD

**Issue by tsi** [preactjs/preact#4095] opened 2023-08-14 06:36 UTC
First, would like to say thanks for all the work you people put into this.

Now, we're developing a feature relying on pointer-events so that we can handle both mouse and touch events easily.
On old Safari, a [polyfill](https://github.com/jquery-archive/PEP) is required for those events to function.
The polyfill seems to work on many demos but I couldn't get it to work in my project.
I tested multiple directions and eventually got to the conclusion that it's probably Preact that is in my way.
Here are two sandboxes:
[This](https://q38ygd.csb.app/) one is using React and works on Safari 12 with the polyfill
[This](https://f4zl39.csb.app/) one has the exact same component but using Preact, not responsive on Safari 12

Can anyone help explain the issue? Is there anything we can do about it?
Thanks!

**Comment by rschristian** [comment] 2023-08-14 07:12
It looks like both of your links are to the same sandbox

**Comment by tsi** [comment] 2023-08-14 07:32
Sorry, the one using Preact is [this one](https://f4zl39.csb.app/). edited the original msg. thanks!

**Comment by rschristian** [comment] 2023-08-14 08:35
Looks like `onGotPointerCapture` and `onLostPointerCapture` get their names mangled due to the `useCapture` check / name coercion:  https://github.com/preactjs/preact/blob/4fea40d1124ba631f8a11c27f6e71e018136318e/src/diff/props.js#L86

This stops the listener from being set correctly, as the event names end up as `GotPointer` and `LostPointer`.

They might need to be special cased here.

**Comment by tsi** [comment] 2023-08-15 08:28
Wow you already have a PR. that's truly amazing! 
Just to make sure we are on the same page - my issue was with the other pointer-events handlers, i.e. `onPointerDown`, `onPointerMove` etc, not `onGotPointerCapture`/ `onLostPointerCapture`
The polyfill for Safari don't work for some reason, while it does work in other places.
Will this fix that?

**Comment by rschristian** [comment] 2023-08-15 12:49
This would do nothing to address those handlers, no.

Can you provide a reproduction? As I previously mentioned, we can't really help you debug your polyfill if you don't include it in the reproduction.

**Comment by tsi** [comment] 2023-08-15 12:55
Oh I really hoped it would...
The examples above already include the polyfill and reproduce the issue, you'll need to open them in Safari 12 to see it (I used BrowserStack)

**Comment by tsi** [comment] 2023-08-15 13:58
No, it's there in both under "external resources", calling [this](https://code.jquery.com/pep/0.4.3/pep.js)

**Comment by tsi** [comment] 2023-08-16 12:05
The point was that the polyfill works fine with React's `onPointerDown`, `onPointerMove` etc
And also with `addEventListener()` `pointerdown`, `pointermove` etc
But not with Preact `onPointer...` props.
Is there anything we can try to make this work?

**Comment by rschristian** [comment] 2023-08-16 12:19
[Preact certainly is using `addEventListener`](https://github.com/preactjs/preact/blob/21a6f301b9d6c2e9551db27308e57bd995c6a51a/src/diff/props.js#L102).

Keep in mind there is a pretty big gap in React and Preact when it comes to events, in that Preact uses DOM events while React does not. I have no idea if that's relevant to this issue but it's good to keep in mind that there are some intentional differences in this area.

**Comment by tsi** [comment] 2023-08-16 13:27
Yes, excuse my excitement :)
Just did a quick POC using BrowserStack. and it seems to work.

**Comment by rschristian** [comment] 2023-08-16 21:30
Glad to hear it!

I don't think there's any action we can take on the Preact side, this is the troublesome line:

https://github.com/preactjs/preact/blob/21a6f301b9d6c2e9551db27308e57bd995c6a51a/src/diff/props.js#L92-L93

I don't believe it's safe to call `.toLowerCase()` blindly, hence the DOM check.

You certainly could patch this behavior, adding `|| /^onPointer/.test(name)` or similar to the conditional, else, you can use the following to fix the TS types to allow `onpointer*`:

```ts
declare module 'preact' {
  namespace JSX {
    interface DOMAttributes<Target extends EventTarget> {
      onpointerdown?: PointerEventHandler<Target> | undefined;
    }
  }
}
```
Just copying the [source types](https://github.com/preactjs/preact/blob/21a6f301b9d6c2e9551db27308e57bd995c6a51a/src/jsx.d.ts#L1289-L1309), but changing event capitalization.

**Comment by tsi** [comment] 2023-08-17 12:02
I really don't mind having it in lowercase, as long as it works on modern browsers, and as long as no other dev sees it and "fixes" it to camelCase.
When we'll be able to drop support for Safari 12 and below, we'll remove the polyfill and fix the pointer-event props to be camelCase.

Thank you so much for the responsiveness here, truly impressive.

**Comment by rschristian** [comment] 2023-08-17 14:26
Going to close this out in that case, let me know if you run into any further issues and we can reopen.

**Closed** 2023-08-17 14:26 UTC
