### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading '__H') when using Preact with react-redux Provider API

### ISSUE THREAD

**Issue by greatvivek11** [preactjs/preact#3261] opened 2021-09-11 07:38 UTC
I'm trying to build a simple Todo App using Preact + Vite + Typescript + Redux. 

This is the error I'm getting when using react-redux Provider API to connect ReduxToolkit store with my <App>.

You can check out my GitHub repo here - https://github.com/greatvivek11/TodoApp
But this code has not been pushed there.

```typescript
Uncaught TypeError: Cannot read properties of undefined (reading '__H')
    at m (react-redux.064eb876.js:3)
    at d (react-redux.064eb876.js:3)
    at d.Provider [as constructor] (react-redux.064eb876.js:1165)
    at d.L [as render] (index.js:506)
    at $ (index.js:178)
    at m (children.js:147)
    at $ (index.js:195)
    at m (children.js:147)
    at $ (index.js:195)
    at M (render.js:36)
```
I have aliased react & react-dom in vite.config.ts to preact-compat.
vite.config.ts
```typescript
export default defineConfig(
  {
  esbuild: {
    jsxFactory: 'h',
    jsxFragment: 'Fragment',
  },
  alias:
    [
       {find: 'react', replacement: 'preact/compat'},
       {find: 'react-dom', replacement: 'preact/compat'},
    ],
  plugins: [
    preactRefresh()
  ],
});
```
Here is my tsconfig.json
```typescript
{
  "compilerOptions": {
    ...
    "paths": {
      "react": ["node_modules/preact/compat"],
      "react-dom": ["node_modules/preact/compat"]
    }
  },
  "include": ["src", "service-worker.js"]
}
```
main.tsx
```typescript
serviceWorker.register();
render(
    <Provider store={store}>
        <App />
    </Provider>,
    document.body!
);
```
package.json
```typescript
{
  ...
  "dependencies": {
    "@reduxjs/toolkit": "^1.6.1",
    "preact": "^10.5.10",
    "react-redux": "^7.2.4"
  },
  "devDependencies": {
    "@prefresh/vite": "^2.0.1",
    "@tailwindcss/typography": "^0.3.1",
    "@types/node": "^16.4.8",
    "@typescript-eslint/eslint-plugin": "^4.14.0",
    "@typescript-eslint/parser": "^4.14.0",
    "autoprefixer": "^10.2.1",
    "cross-env": "^7.0.3",
    "dotenv": "^10.0.0",
    "postcss-import": "^14.0.2",
    "prettier": "^2.2.1",
    "tailwindcss": "^2.0.2",
    "typescript": "^4.1.3",
    "vite": "^2.0.0-beta.31"
  },
 ...
}
```

**Comment by marvinhagemeister** [comment] 2021-09-11 13:09
Thanks for notifying us of an issue. The configs don't help much to pin point or debug this issue. Can you share how the component looks like that triggers the error? That's the most important information to be able to solve this.

**Comment by greatvivek11** [comment] 2021-09-11 15:30
Hi Marvin. Thanks for replying.  The code is somewhat messy. I'm still working on it. It's long. Perhaps you can get a better idea from https://github.com/greatvivek11/TodoApp/tree/Feature_Tasks/src.

Main.tsx
```typescript
import { render, h, hydrate } from 'preact';
import { App } from './app';
import './index.css';
import * as serviceWorker from './Components/ServiceWorker';
import { Provider } from 'react-redux';
import { store } from './redux/store';

render(
    <Provider store={store}>
        <App />
    </Provider>,
    document.getElementById('app')!
);
```
App.tsx

```typescript
import { h } from 'preact';
import { useEffect, useState } from 'preact/hooks';
import { getTasks, updateTasks } from './Service/Service';
import AddTasks from './Components/Tasks/AddTasks';
import CompletedTask from './Components/Tasks/CompletedTask';
import ActiveTask from './Components/Tasks/ActiveTask';
import { Task } from './Model/Task';
import { TaskStatus } from './Model/TaskStatus';
import * as dotenv from 'dotenv';
import Footer from './Components/Footer';
import { useSelector } from 'react-redux';
import { RootState } from './redux/store';
import { Tasks } from './Model/Tasks';

export const App = () => {
  const Tasks = useSelector((state: RootState) => state);

  const initialActiveTasks: Task[] = (localStorage.getItem("ActiveTasks") !== null) ? JSON.parse(localStorage.getItem("ActiveTasks")!!) : [];
  const initialCompletedTasks: Task[] = (localStorage.getItem("CompletedTasks") !== null) ? JSON.parse(localStorage.getItem("CompletedTasks")!!) : [];
  const [ActiveTasks, setActiveTasks] = useState<Task[]>(initialActiveTasks);
  const [CompletedTasks, setCompletedTasks] = useState<Task[]>(initialCompletedTasks);
  const [UpdateTasks, setUpdateTasks] = useState(false);

  function onCheck(index: number): void {
    const completedTask = ActiveTasks[index];
    completedTask.status = TaskStatus.Completed;
    setCompletedTasks([...CompletedTasks,completedTask]);
    onDelete(index);
  }
  function onDelete(index: number): void {
    ActiveTasks.splice(index, 1);
    setActiveTasks([...ActiveTasks]);
    setUpdateTasks(true);
  }
  function onAddTask(tasks: Task[]):void {
    console.log(tasks);
    setActiveTasks([...tasks]);
    setUpdateTasks(true);
  }
  function onUncheck(index: number): void {
    const deleteCompletedTask = CompletedTasks[index];
    deleteCompletedTask.status = TaskStatus.Active;
    setActiveTasks([...ActiveTasks, deleteCompletedTask]);
    CompletedTasks.splice(index, 1);
    setCompletedTasks([...CompletedTasks]);
    setUpdateTasks(true);
  }

  useEffect(() => {
    localStorage.setItem('ActiveTasks', JSON.stringify(ActiveTasks));
  }, [ActiveTasks])

  useEffect(() => {
    localStorage.setItem('CompletedTasks', JSON.stringify(CompletedTasks));
  }, [CompletedTasks])

  function returnLineBreak(): any {
    if (Tasks.completedTasks.length > 0 && Tasks.activeTasks.length > 0) {
      return (
        <hr />
      );
    }
  }

  console.log("Active Tasks: " + Tasks.activeTasks.length);
  console.log("Completed Tasks: " + Tasks.completedTasks.length);

  return (
    <div className="container mx-auto lg:w-1/2">
      <h1 className="text-5xl">Todo App</h1>
      <AddTasks />
      <ActiveTask />
      {returnLineBreak()}
      <CompletedTask CompletedTasks={Tasks.completedTasks} onDelete={onUncheck} />
      <Footer />
    </div>
  );
}
```

**Comment by alexsorokoletov** [comment] 2021-10-21 07:16
We're getting the exact same error message and it seems to be related to the `useEffect` hook:
The minified useEffect hook from preact package:
```
function y2(r5, o4) {
  var i5 = m2(t2++, 3);
  !n.__s && k2(i5.__H, o4) && (i5.__ = r5, i5.__H = o4, u2.__H.__h.push(i5));
}
```

**Comment by JoviDeCroock** [comment] 2021-12-03 17:56
Just tried this which seems to all work correctly, this might be an issue with your bundle producing multiple copies of Preact, [working example](https://codesandbox.io/s/intelligent-banach-xu52d?file=/src/index.js) closing until we have a way to reproduce this.

**Closed by JoviDeCroock** 2021-12-03 17:56 UTC
Labels: needs-more-info
