### ISSUE TITLE
Issue with Suspense + Lazy + @reach/router

### ISSUE THREAD

**Issue by ryansolid** [preactjs/preact#2176] opened 2019-12-10 23:17 UTC
Reach Router(https://github.com/reach/router) has an issue where it doesn't seem to trigger re-render once the Suspended Component is ready. In my projects if I navigate away and then come back again or do something to cause the parent to re-render suddenly the content is there. But otherwise it never shows on its own. 

There appears to be no errors in the console. The content just does not appear as expected if Suspense is triggered on render.

I forked the sandbox for a React Router issue(which seems now to be fixed in 10.1.0). This example uses @react/router instead and appears to still be broken:
https://codesandbox.io/s/preact-suspense-lazy-issue-tdfjc

**Comment by sventschui** [comment] 2020-01-05 13:14
Sorry for the late response. This is caused by the `RouterImpl` extending `PureComponent` and therefore blocking updates by returning false in `shouldComponentUpdate`.

This shortcoming of our Suspense implementation will be addressed in #2125 but we could not yet come up with a working solution.

**Closed** 2020-02-02 17:25 UTC
Labels: bug
