### ISSUE TITLE
Possible race condition leading to "TypeError: Cannot read property 'context' of undefined"

### ISSUE THREAD

**Issue by PaulBlanche** [preactjs/preact#3220] opened 2021-07-07 18:14 UTC
**Describe the bug**
There seems to be a race condition related to `useContext` with `Suspense` and `preact-ssr-prepass`. In my application i use `usePromise` (from `react-promise-suspense`) to await on certain computation server-side.

Sometimes (but not systematically) the ssr prepass fails with this error :
```
error TypeError: Cannot read property 'context' of undefined
    at Object.exports.useContext (.../frugal/node_modules/preact/hooks/src/index.js:239:36)
    at Object.useAssertCreator (.../frugal/packages/preact-render/src/asset.ts:8:32)
    at Object.useImage (.../frugal/packages/preact-render/src/useImage.ts:8:26)
    at d.call (.../frugal/packages/ulule/src/pages/project/descriptor.tsx:50:20)
    at t (.../frugal/node_modules/preact-ssr-prepass/src/index.js:82:22)
```

If i remove the longest computations (the ones that would need to be awaited on the most during the ssr prepass), the error disappears. If i replace the computation with a simple timeout, the error still happens. That's why i suspect a race condition. I don't know if this is an issue with `preact` or `preact-ssr-prepass`.

**To Reproduce**
I could not reproduce this issue with a simplified setup on CodeSandbox. I could share my codebase if needed but there is a lot of moving parts.

**Expected behavior**
When a value is passed to a `context.Provider`, a `useContext` should return this value even in the context of an ssr prepass.

**Comment by PaulBlanche** [comment] 2021-07-08 08:30
It seems that some promise are not awaited on in `preact-ssr-prepass`, and a component's promise resolves after i call `render`. From what i understand, this error where `currentComponent` is undefined happens when a hook is called outside of a render path.

I think all promise that need to be awaited on a throwed in component, so i don't understand how `preact-ssr-prepass` could miss one. I'll check on that, and maybe open an issue on `preact-ssr-prepass` instead ?

**Comment by PaulBlanche** [comment] 2021-07-08 12:20
I managed to reproduce the bug here : https://github.com/PaulBlanche/preact-bug-reproduction
Strangely, the same code in codesandbox runs without errors.

**Comment by PaulBlanche** [comment] 2021-08-04 07:12
Does anybody have some pointer for where i should look to try and understand the problem ?

**Comment by dancras** [comment] 2022-02-11 11:20
I think I've just encountered this same error in a different context. I've managed to narrow it down to a very simple failing example: https://github.com/dancras/preact-bug

 - Error only occurs with `useContext`. Using `Context.Consumer` works as expected
 - Error occurs in `vitest` but not `jest` so likely some race condition as mentioned above

```
TypeError [Error]: Cannot read properties of null (reading 'context')
    at Proxy.exports.useContext (/app/node_modules/preact/hooks/dist/hooks.js:1:2437)
    at d.ExampleConsumer [as constructor] (/app/app/src/preact-bug.test.jsx:38:41)
    at d.M [as render] (/app/node_modules/preact/dist/preact.js:1:7837)
    at j (file:///app/node_modules/preact/dist/preact.mjs:1:5752)
    at file:///app/node_modules/preact/dist/preact.mjs:1:1494
    at Array.some (<anonymous>)
    at g (file:///app/node_modules/preact/dist/preact.mjs:1:1392)
```

**Comment by marvinhagemeister** [comment] 2022-02-13 23:06
@dancras Looking at that output it seems like `vitest` is including two different versions of Preact. Hooks require by design a singleton and multiple Preact versions don't know about each other. That's why the context value is missing and the error only pops up with hooks. Here in particular it includes `preact.mjs` (ESM Module) and `preact.js` (CommonJS Module).

Reported it upstream at https://github.com/vitest-dev/vitest/issues/747

**Comment by PringlePot** [comment] 2022-04-18 16:59
This also happens when using useSWR with preact

**Comment by JoviDeCroock** [comment] 2022-06-03 07:45
Closing as this should be fixed upstream by preact-testing-library adding the ESM build

**Closed by JoviDeCroock** 2022-06-03 07:45 UTC
Labels: upstream

**Comment by rhengles** [comment] 2023-03-08 19:45
It sounds like my React-router problem might be related to this!

https://github.com/preactjs/preset-vite/issues/73

[Link to CodeSandbox](https://codesandbox.io/p/sandbox/weathered-forest-319pfq)

For me the error _always_ happens.

As I commented on the issue above, when I use react-router 5.x the app works, including with SSR. But it fails the moment I try to get a hook from the router, be it `useLocation()` or `useHistory()`.
