### ISSUE TITLE
对antd-mobile兼容性问题

### ISSUE THREAD

**Issue by 99414041** [preactjs/preact#1889] opened 2019-08-20 07:34 UTC
preact配合antd-mobile 的picker组件，当滚动picker子元素，picker容器会消失

**Comment by marvinhagemeister** [comment] 2019-08-20 09:05
English please. Seeing the words `antd-mobile` in there I'm guessing that this is a duplicate of #1890

**Closed by marvinhagemeister** 2019-08-20 09:05 UTC
