### ISSUE TITLE
My IDE report Error `Its type '"p"' is not a valid JSX element type.`

### ISSUE THREAD

**Issue by XLearner** [preactjs/preact#3984] opened 2023-04-25 02:59 UTC
I imported preact into my project and the project worked successfully. However, the VSCode had always the following error message:

![image](https://user-images.githubusercontent.com/26158725/234163149-fd3970e8-c521-416e-ad91-a6f26df1e463.png)

I can use `// @ts-expect-error` to shield this error, but I want to get a more gentle way to deal with this. 

Could anyone help? 🤜🏽

**Comment by rschristian** [comment] 2023-04-25 03:06
Have you restarted the TS language server?

What does your `tsconfig.json` look like?

**Comment by XLearner** [comment] 2023-04-25 04:29
Here is my `tsconfig.json`:
```
{
  "compilerOptions": {
    "sourceMap": true,
    "jsx": "preserve",
    "jsxImportSource": "preact",
    "jsxFactory": "h",
    "jsxFragmentFactory": "Fragment",
    "target": "es5",
    "module": "commonjs",
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true
  }
}
```

**Comment by rschristian** [comment] 2023-04-25 05:38
Remove `"jsxImportSource": "preact"`, it shouldn't be set unless you're using the automatic JSX transform. I don't think that'll be a problem per se though.

I have to imagine it's just a temporary bug in your editor, as everything else it looks fine. Give your editor a restart it you haven't already, or try to reproduce the issue in something like codesandbox if it persists.

**Comment by XLearner** [comment] 2023-04-25 07:03
It is no work of removing `"jsxImportSource": "preact"`. And I've tried to restart TS Server, during the restarting process, this error message is gone, but appears after the restarting is done.
I try to reproduce the issue in a codesandbox but fail, I notice the declaration tips are different, like the following image. The reason for the difference is that I import `h` by hand, if I don't do that there will have a problem in runtime that can not transform `React.createElement` to `h`. However, even if I remove the `h`, this issue is still there.😭

![image](https://user-images.githubusercontent.com/26158725/234199334-bfaaecab-b672-4760-97c1-a3c3f07e6e6c.png)

**Comment by XLearner** [comment] 2023-04-25 08:05
Thank you very much for your patient reply. I have tried all the methods mentioned in the document, but none of them have worked. I will use comments `// @ts-expect-error` as a temporary solution to avoid this error, and then I will look for a solution later. Thank you.

**Comment by davidmz** [comment] 2023-04-25 18:39
Here is my minimal repository with the same problem: https://github.com/davidmz/preact-types-test

![image](https://user-images.githubusercontent.com/132120/234371306-ce7c0010-4e6f-4ac4-a5e4-04a2ae966625.png)

**Comment by rschristian** [comment] 2023-04-25 21:00
I'm a bit surprised to see 3 (seemingly unrelated) people have the same issue. Is this specifically an issue with the latest or recent versions of Preact? Do you still see this if you go back a bit (say, mid v10)?

**Comment by marvinhagemeister** [comment] 2023-04-26 05:28
@lm-maxfab Thanks for sharing that repo. Weirdly I'm unable to reproduce that on my end. VSCode finds the correct JSX types. Works in both the stable release line and vscode insiders for me. Note that `esbuild` doesn't do any type checking. It just deletes the types, so any type errors would be ignored by it.

<img width="618" alt="Screenshot 2023-04-26 at 07 22 20" src="https://user-images.githubusercontent.com/1062408/234477110-9b0ec60c-d52d-4a6e-9be7-99c604203d8b.png">

@davidmz I'm getting a 404 on that link. Is the repo private?

**Comment by davidmz** [comment] 2023-04-26 07:32
@marvinhagemeister oh, sorry, it really was private. I've now made it public.

But now I see the same error with clean `pnpm create vite test-app --template preact-ts`, so I doubt that Preact is the problem. It looks more like something is broken in our VSCode settings...

**Comment by davidmz** [comment] 2023-04-26 07:41
Well, my VSCode had the [ms-vscode.vscode-typescript-next](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next) extension installed. I disabled it, and that seemed to fix the problem, at least for me. Sorry, I didn't check that at first.

**Comment by rschristian** [comment] 2023-04-26 07:44
Interesting, maybe should raise this on that extension's tracker.

@lm-maxfab and @XLearner, do you have this installed too by chance?

**Comment by davidmz** [comment] 2023-04-26 08:06
I see there is a recent bug in Typescript that looks similar: https://github.com/microsoft/TypeScript/issues/53939. Maybe the extension was using the nightly version with this bug.

**Comment by lm-maxfab** [comment] 2023-04-26 09:27
> @lm-maxfab and @XLearner, do you have this installed too by chance?
Yep, had it installed too, everything's fine when disabling it. Thanks a lot!

**Comment by XLearner** [comment] 2023-04-27 02:16
> Interesting, maybe should raise this on that extension's tracker.
> 
> @lm-maxfab and @XLearner, do you have this installed too by chance?

Wow, that's really the key to the problem. After reloading this plugin, there is no issue anymore. Thank you very much!

**Comment by JoviDeCroock** [comment] 2023-04-27 09:09
Closing this as it seems to be a genuine TS related bug, for anyone finding this thread, disabling `[ms-vscode.vscode-typescript-next](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next)` fixes the issue.

**Closed by JoviDeCroock** 2023-04-27 09:09 UTC
Labels: types
