### ISSUE TITLE
Devtools error when trying to jump to non existing DOM node

### ISSUE THREAD

**Issue by AEnterprise** [preactjs/preact#1731] opened 2019-06-22 13:04 UTC
if you have react nodes in the debug view that are not in the DOM tree (i had 3 nested preact routers leading to dupes showing up there that are not in the the tree, only show up when searching)

if you then right click one of those nodes and try to jump to the DOM node you get the "oh snap something went wrong" screen as the page crashed and the devtools disconnect

**Comment by robertknight** [comment] 2019-06-24 18:46
By "debug view" do you mean the React DevTools Chrome extension?

Can you provide us with step-by-step instructions that will enable us to reproduce the problem, including details of the Chrome version, Preact version and React devtools extension? Without this we are unlikely to be able to fix the problem.and will need to close the issue.

**Comment by AEnterprise** [comment] 2019-06-26 07:40
yes i mean the react devtools view

chrome version:  75.0.3770.100
react extention: 3.6.2
preact version: 10.0.0-beta.2

basic repro is just making it dupe nodes, this can easily be done if you just go to any page made in preact, use the react tool filter to look for a specific component and trigger a hotreload with adding blank lines in the code or so (make sure it actually saves though, VSC auto styling could remove them again before saving), see how there now are double the searched node, pick the one that is 0px large and try to jump to it

**Comment by robertknight** [comment] 2019-06-26 08:55
>  trigger a hotreload with adding blank lines in the code or so 

"Trigger a hotreload" with what? A Webpack dev server + a hot reloading plugin of some kind? If you could put up a gist or GitHub repo that contains a minimal set of files needed to reproduce the issue then it is much more likely this will get looked at.

**Comment by AEnterprise** [comment] 2019-06-26 09:31
@robertknight i'm using the preact cli

not doing anything special so just the preact cli default template should work with "npm run development"

**Comment by marvinhagemeister** [comment] 2020-01-14 12:24
Closing this issue as it was only relevant for our `react-devtools` bridge. All development regarding devtools are aimed at `preact-devtools` where I can't reproduce the described error.

**Closed by marvinhagemeister** 2020-01-14 12:24 UTC
Labels: legacy-devtools, needs-more-info
