### ISSUE TITLE
Context.Provider not taking child elements

### ISSUE THREAD

**Issue by lockieluke** [preactjs/preact#4036] opened 2023-06-04 19:49 UTC
- [x] Check if updating to the latest Preact version resolves the issue

**Describe the bug**

Don't know if it's a TypeScript problem or not.

`Context.Provider` doesn't take child elements directly
![image](https://github.com/preactjs/preact/assets/25424409/66770536-64a3-4e7a-8139-7e9e77e919be)
But works just fine if they are passed into the prop `children`
![image](https://github.com/preactjs/preact/assets/25424409/bbbf0e67-4a27-45c5-a759-5b5db928f3f4)

The app works just fine either way

**Comment by marvinhagemeister** [comment] 2023-06-05 21:31
Thanks for filing an issue. Can you share with us how we can reproduce the shown error? I've been unable to reproduce that so far.

**Comment by Pyrolistical** [comment] 2023-07-19 03:24
@marvinhagemeister I was able to repoduce this: https://github.com/Pyrolistical/preact-typescript-children-bug
![Screenshot 2023-07-18 202236](https://github.com/preactjs/preact/assets/463642/8dd7abe6-26a2-4164-a0dc-014271f93eaf)

> Type '{ value: string; }' is not assignable to type 'RenderableProps<{ value: string; children: ComponentChildren; }, any>'.
  Property 'children' is missing in type '{ value: string; }' but required in type '{ value: string; children: ComponentChildren; }'.

It is pointing to this line: https://github.com/preactjs/preact/blob/5a56a830b6abf23009d7e2b5a0d0b7707a86a8e8/src/index.d.ts#L379

**Comment by Pyrolistical** [comment] 2023-07-19 03:31
It runs correctly. Purely a typing issue. Could be a typescript/jsx issue as `children` is special

**Comment by JoviDeCroock** [comment] 2023-11-11 09:05
Fixed in #4205

**Closed** 2023-11-11 09:06 UTC
Labels: types, needs-more-info
