### ISSUE TITLE
preact.render third argument causes weird behavior

### ISSUE THREAD

**Issue by laino** [preactjs/preact#1896] opened 2019-08-26 11:48 UTC
https://codepen.io/laino/pen/XWrMyda?editors=0010 Edit: fixed link.

When using the third "replace node" argument, you won't get anything at all.

Comment either of those ``render`` and it will work.

**Comment by hectorromo** [comment] 2019-08-26 12:53
@laino The render function has changed and works now out of the box like you'd expect it to. Repeated renders will correctly render into the container instead of always appending to it.
https://github.com/marvinhagemeister/preact-faq/blob/master/migrate-to-x.md#remove-the-3rd-argument-to-render

**Comment by laino** [comment] 2019-08-26 14:26
@hectorromo The TypeScript types don't reflect that though and clearly the third argument does *something*.

**Comment by JoviDeCroock** [comment] 2019-08-26 14:27
It's the replaceNode argument that got added back in a later release. https://preactjs.com/guide/v10/api-reference/#render

**Comment by laino** [comment] 2019-08-26 14:31
@JoviDeCroock It doesn't work though. As shown in that codepen. It just removes everything.

**Comment by laino** [comment] 2019-08-26 14:32
Wait.... I linked the wrong codepen.

**Comment by laino** [comment] 2019-08-26 14:36
https://codepen.io/laino/pen/XWrMyda?editors=0010

Here's the right one.

**Comment by JoviDeCroock** [comment] 2019-08-26 14:44
This thirth argument does not work for the `/compat` only for the pure Preact

**Comment by laino** [comment] 2019-08-26 14:50
@JoviDeCroock It's not using compat? At least not unless there's some magic happening I'm not aware of.

**Comment by JoviDeCroock** [comment] 2019-08-26 14:51
I've made a small example to show it works since I can't edit on codepen: https://codesandbox.io/s/pensive-mahavira-jgh4h

**Comment by laino** [comment] 2019-08-26 14:53
@JoviDeCroock Your example doesn't use ReactX

**Comment by laino** [comment] 2019-08-26 14:54
@JoviDeCroock I fixed it to demonstrate the broken behavior:

**Comment by laino** [comment] 2019-08-26 14:55
You'd expect to see "3" there, but instead you get an empty element.

**Comment by JoviDeCroock** [comment] 2019-08-26 14:56
Well again, you are double rendering. I don't see the point in that let's maybe look at what use case that is used for?

**Comment by laino** [comment] 2019-08-26 14:57
It even happens when you render something different. It doesn't have to be the same element.

**Comment by laino** [comment] 2019-08-26 15:00
@JoviDeCroock There, now I'm trying to render something different and have it replace the result of my first render: https://codesandbox.io/s/cool-fog-zl4jj

**Comment by laino** [comment] 2019-08-26 15:00
Except.... you get nothing.

**Comment by JoviDeCroock** [comment] 2019-08-26 15:04
Please do not use passive aggressive language, I've pointed out the issue in saying that you're using `render` twice this is probably the root cause of your issue.

Then I showed you an example which has working output, it replaces the existing DOM with correct diffed DOM. This comes in handy when using prerendering and related.

https://codesandbox.io/s/vigilant-kare-x9lbc

**Comment by laino** [comment] 2019-08-26 15:14
>Please do not use passive-aggressive language

I can do that. In return please try to take your time to actually understand the reported problem before giving an that has nothing to do with it and is a workaround at best.

Again: The problem is that the ``replaceNode`` doesn't actually work. Meaning: Not as documented.

It's supposed to either replace the specified node or update it. Instead you get an empty element.

**Comment by marvinhagemeister** [comment] 2019-08-27 06:53
> > Please do not use passive-aggressive language
> 
> I can do that. In return please try to take your time to actually understand the reported problem before giving an example that has nothing to do with it and is a workaround at best. That was absolutely infuriating.

Please re-read our [Code of Conduct](https://github.com/preactjs/preact/blob/master/CODE_OF_CONDUCT.md) again. We don't tolerate passive aggressiveness as it's in direct violation of our CoC, so we have to flag this. There is never a need to be rude even if commenters may be talking past each other. A good step forward would be to apologize to @JoviDeCroock and than let's get back onto solving this issue :+1: 

There does indeed seem to be an issue lurking with the `replaceNode` parameter. Not rendering twice is a valid workaround in the short term, but that's obviously not a long-term solution.

**Comment by laino** [comment] 2019-08-27 10:36
>  A good step forward would be to apologize to @JoviDeCroock 

I am sorry for my choice of metaphorical language.

> and than let's get back onto solving this issue +1

Yes, please.

**Comment by cristianbote** [comment] 2019-08-28 05:52
Hey @laino, @JoviDeCroock did a fix for your reported issue. The test case is your exactly what you've reported so I'm confident this is fixed.

If there's anything else and this is not working for your needs let us know. Closing it now.

**Closed by cristianbote** 2019-08-28 05:52 UTC
