### ISSUE TITLE
VBulletin conflicts with jsx using strings

### ISSUE THREAD

**Issue by johncburnette** [preactjs/preact#3006] opened 2021-02-12 20:57 UTC
Hey guys,

Brought this up on slack and wanted to drop some info on an issue I'm seeing when preact is loaded with VBulletin. One of our publishers runs a forum and reported that headlines are not displaying properly. You can see this in this screenshot
![image](https://user-images.githubusercontent.com/56326230/107820460-d5626380-6d48-11eb-8ad6-749797da05d1.png)

As far as the code for building this, we use the following component:

```
export const WidgetContent = ({ headline, description, provider }) => (
  <div>
    <h4>{ headline }</h4>
    <div>{ description }</div>
    <div>{ provider }</div>
  </div>
);
```

There's some other tooling in this for class names as we use emotion for style but I've omitted them as they're just visual noise but as you can see there's not a lot going in this component, just 3 string values being passed here.

We're using Preact 10.3.3 and Preact CLI 3.0.1 as we opt to be cautious on NPM package upgrades in our repos. For what it's worth, this is the only place I've seen this happen. Outside of this site, everything is running smoothly and we rarely have any issues that aren't caused by code we're writing ourselves. I spent most of the day trying to make sense of this and finally stumbled onto a VBulletin script named vbulletin_global:

![image](https://user-images.githubusercontent.com/56326230/107821272-245cc880-6d4a-11eb-828f-eb9717be0a39.png)

Through trial and error I found that removing this script fixes the issue shown above in the screenshot. As a workaround, we can isolate our widget into an iframe and have it render as expected but I'm curious as to what your thoughts are on this and if there's anything that can be done to get around this. I've included a link to a testing page showing the issue in question here in [this link](https://code.revcontent.com/performante/SW/index.htm).

**Comment by marvinhagemeister** [comment] 2021-02-12 23:57
This bug seems to be caused by the `props` normalization in `preact/compat` being wrongly applied on text nodes which have no props, only strings. This was fixed in [Preact 10.4.0}(https://github.com/preactjs/preact/releases/tag/10.4.0) and here is [the PR](https://github.com/preactjs/preact/pull/2410) that fixed it.

I'm not 100% sure on the reason why it only pops up when the `vbulletin` script is included, very likely comes down to the fact that that script is messing with the native `String` object. It attaches and overwrites a bunch of properties.

An upgrade to the latest Preact version will resolve this issue. I can relate to being cautious with upgrades of any library for a production site, but I'd highly recommend giving the latest Preact release a go.

**Closed** 2021-02-13 00:21 UTC
