### ISSUE TITLE
Cannot read property 'insertBefore' of undefined when using `Suspense` and `lazy`

### ISSUE THREAD

**Issue by pt-hoang** [preactjs/preact#3149] opened 2021-05-12 06:55 UTC
- [x] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
`Cannot read property 'insertBefore' of undefined` when using `Suspense` and `lazy`. Reason being `originalParent` is undefined in `Suspense`'s `removeOriginal` function

Works if checks `originalParent` before calling `insertBefore` on it
![image](https://user-images.githubusercontent.com/84064700/117931561-e748a800-b331-11eb-9783-0872dfa215ef.png)

**To Reproduce**

If possible, please provide a CodeSandbox/Codepen that demonstrates the issue. You can use the following template: https://codesandbox.io/s/immutable-grass-ziq4b?file=/src/index.js

In codesandbox

**Expected behavior**
No error

**Comment by developit** [comment] 2021-05-16 22:47
I think someone else ran into this as well. Not 100% sure what the root cause is.

**Comment by Nedomas** [comment] 2021-07-18 09:38
I have the same problem when state above suspense changes. Did you find the solution @pt-hoang ? I understand this is preact only bug?

**Comment by JoviDeCroock** [comment] 2021-11-15 11:11
Seems like a duplicate of https://github.com/preactjs/preact/issues/3105 let's track there

**Closed by JoviDeCroock** 2021-11-15 11:11 UTC
