### ISSUE TITLE
Exception in Slate (RTE) when pressing enter or backspace

### ISSUE THREAD

**Issue by shhlkien** [preactjs/preact#2789] opened 2020-10-06 13:34 UTC
I use slate (https://docs.slatejs.org/) with preact, all things in the latest version. The problem begins when I used preact hooks.
Slate provides rich text editor and comes from react. When used it with react, everything is ok, but when used preact, my app was crashed.
I think there is a problem with preact hooks
This problem only occurs in Firefox

### Reproduction
Error screen:
![image](https://user-images.githubusercontent.com/23404165/95208199-fc48e000-0812-11eb-90db-ceaec9795d76.png)

Sandbox: https://codesandbox.io/s/youthful-boyd-z3l36

### Steps to reproduce
Run the app, type something then press `enter` or `backspace`

### Expected Behavior
The Slate editor adds new line or deletes characters

### Actual Behavior
App is crashed

**Comment by shhlkien** [comment] 2020-10-06 14:01
For the title, I've tested [draft-js](https://draftjs.org/) and the result is same. This is a hooks problem.

**Comment by sventschui** [comment] 2020-10-27 07:24
This is not related to hooks but rather FF not implementing onBeforeInput but slate relying on it. React ships a rather incomplete polyfill that breaks with spellcheck/autocorrect.

I'll close this as a duplicate of https://github.com/preactjs/preact/issues/1422, have a look at the comment I just left there.

**Closed by sventschui** 2020-10-27 07:24 UTC
