### ISSUE TITLE
[10.0.0-rc.1] Component with conditional render result forces remount of siblings

### ISSUE THREAD

**Issue by alebastr** [preactjs/preact#1829] opened 2019-08-02 21:30 UTC
Codepen: <https://codepen.io/alebastr/pen/ZNgWPZ?editors=0010#0>

Certain wrapping component causes preact to remount all subsequent siblings without calling any lifecycle methods. However, when I inline the same logic (`{this.props.open && <Modal {...this.props} />}`), it works correctly. 
```javascript
class Wrapper extends React.Component {
    render() {
        if (this.props.open) {
            return <Modal {...this.props} />;
        }
        return null;
    }
}
```
From the codepen you can see that the button before the wrapper component preserves focus, but the button after does not. This happens because after unmounting Wrapper and returning focus, preact temporarily removes second button from DOM.

The issue was introduced between 10.0.0-beta.0 and 10.0.0-beta.1.

**Comment by JoviDeCroock** [comment] 2019-08-07 17:46
It also should be fixed with `this.props.open ? <Modal /> : null`. I know this isn't a fix yet but it does make it easier than always making wrappers. The problem is that this is quite a hard problem since we are dealing with offsets here and there is no way to say the DOM-node that was at position 4 has moved to position 3. That's why this delete + insert happens.

A potential fix would be to reintroduce our .focus code.

**Comment by JoviDeCroock** [comment] 2024-01-02 10:36
Fixed in latest

**Closed by JoviDeCroock** 2024-01-02 10:36 UTC
Labels: bug
