### ISSUE TITLE
TypeScript definition render() problem

### ISSUE THREAD

**Issue by NekR** [preactjs/preact#830] opened 2017-08-23 20:03 UTC
https://github.com/developit/preact/blob/0dea3b77ee0677987815347c1e6bd23821728aa2/src/preact.d.ts#L66

So, this definition doesn't seem to work. I have to do something like this to make it work:

```ts
interface Props {
  item: any;
}

class Item extends Component<Props, any> {
  render({ item }: Props) {
    return <div class="item">
      {item.title}
    </div>;
  }
}
```

**Comment by developit** [comment] 2017-08-23 20:16
Think its a TS version thing?

**Comment by NekR** [comment] 2017-08-23 22:59
Probably. I'm laster Preact and TS for a new project.

That's just an example with `any`. I kinda prefer it without types at all, but feel like for a big project it's better for types. The problem there is it I cannot just do `render({ item })` -- it doesn't recognise the type of the props passed to it, so I have to add the type manually (`: Props` thing).

I'm not a TypeScript definition pro and I actually have no idea how to fix it, so filed this issue.

**Comment by developit** [comment] 2017-08-23 23:08
^ exactly my feeling. TBH I'd rather have loose definitions (`any`) than have people run into cases where the definition is incorrect.

**Comment by valotas** [comment] 2017-09-03 12:39
I do not think that ts can infer the types there. I rely on `this.props` in order not to redefine the props on every render function

**Comment by mdekrey** [comment] 2018-01-12 13:56
The React types have the same issue, and get a lot of attention. Unless a future version of TypeScript comes out that supports this inheritance, this could probably be closed.

**Comment by leebenson** [comment] 2018-02-17 05:50
Yeah, this is a Typescript issue. Consider this minimal example in the [TS playground](http://www.typescriptlang.org/play/#src=interface%20Person%20%7B%0D%0A%20%20%20%20name%3A%20string%3B%0D%0A%20%20%20%20age%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Aabstract%20class%20Test%3CT%3E%20%7B%0D%0A%20%20%20%20props%3A%20T%3B%0D%0A%20%20%20%20abstract%20render(arg1%3A%20T)%3B%0D%0A%7D%0D%0A%0D%0Aclass%20ConcretePerson%20extends%20Test%3CPerson%3E%20%7B%0D%0A%20%20%20%20render(person)%20%7B%0D%0A%20%20%20%20%20%20%20%20this.props.%0D%0A%20%20%20%20%7D%0D%0A%7D):

<img width="628" alt="screen shot 2018-02-17 at 05 42 09" src="https://user-images.githubusercontent.com/719722/36338393-99d2c4c2-13a5-11e8-8cb1-9fd3168c333a.png">

In the above, `this.props` is correctly inferred to be of type `Person`.

Yet, the argument passed into the function - despite being part of the overridden function signature (TS will balk if you pass into a non-`Person` instance) - is incorrectly inferred as `any`:

<img width="581" alt="screen shot 2018-02-17 at 05 45 13" src="https://user-images.githubusercontent.com/719722/36338402-ebbfa840-13a5-11e8-8922-0b75653d1496.png">

Preact is doing the right thing in its type definitions; if/when TS fix it, it should just work.

Until then, your options are:

1. Explicitly define the type in the `render()` args list, or...
2. Use `this.props`.

FWIW, I do the latter. It means I define the types in one place and screw up less often, whilst also cleaning up the `render()` call (I never understood the point of explicitly passing in props, when they're already set on `this.props` anyway.)

**Comment by developit** [comment] 2018-03-19 16:24
Really hoping to see a fix for this 🐙

**Comment by marvinhagemeister** [comment] 2018-03-20 10:56
mh... I can't reproduce this issue on the playground. The typings are correctly inferred there.

<img width="731" alt="screen shot 2018-03-20 at 11 38 30" src="https://user-images.githubusercontent.com/1062408/37650177-72395abe-2c34-11e8-86b9-4c2d222bb7d7.png">

But somehow I can't get this to work with our typings. Will investigate further.

**Comment by marvinhagemeister** [comment] 2018-05-03 08:07
Seems like this is the bug that we are encountering: https://github.com/Microsoft/TypeScript/issues/21734

**Comment by pmkroeker** [comment] 2019-05-14 14:56
As a follow up to those now coming to this issue, it seems (per the issue @marvinhagemeister posted) that this is the intended usage (issue was updated March 2019). So I guess we're stuck with:
```typescript
render ({...props}: Props) {}
//OR
render () {
  this.props...
}
```

**Comment by mindplay-dk** [comment] 2019-05-14 19:17
I didn't think the `render()` method received props as an argument anymore?

(Why does it? You can already access them using `this.props` - why do we need a second way to do that?)

**Comment by JoviDeCroock** [comment] 2019-05-14 19:18
@mindplay-dk accessing this as a keyword always introduces extra overhead in terms of bundle size, this way you can surpass that hurdle.

**Comment by mindplay-dk** [comment] 2019-05-14 19:30
Yeah, then you need the extra type-hint.

I've been bothered by this before - it's been a minor annoyance, nothing too grievous for me.

And it's just an annotation with no effect on bundle size, so... I just add it and move on.

(Incidentally, constructors also can't be abstracted and can't inherit anything - so you'll duplicate the type-hint for the props argument in constructors as well. It's not perfect.)

**Comment by JoviDeCroock** [comment] 2024-11-01 11:47
Closing this as a TS issue

**Closed by JoviDeCroock** 2024-11-01 11:47 UTC
Labels: help wanted, types
