### ISSUE TITLE
v10.0.0-rc.0 fragment members added out order on first render - but in correct order after update.

### ISSUE THREAD

**Issue by russwyte** [preactjs/preact#1777] opened 2019-07-16 02:01 UTC
I occasionally preact injects the members of a fragment (in my case the fragment has only two vnodes) in the reverse order they are defined. As soon as I re-render they appear in the correct order. This tends to happen when say 3 or 4 of the same type of fragment is appended to the parent.

**Comment by marvinhagemeister** [comment] 2019-07-16 04:49
Can you share a codesandbox or a repo where the issue can be reproduced?

**Comment by marvinhagemeister** [comment] 2019-07-16 06:28
Just tried to re-create the situation like you described, but I'm unable to find any issues with it. This snippet works fine, so it looks like you're doing something different in your code.

```jsx
function App() {
  let [v, set] = useState(0);

  return (
    <div>
      <button onClick={() => set(++v)}>update</button>
      <Fragment>
        <div>A</div>
        <div>B</div>
      </Fragment>
      <Fragment>
        <div>C</div>
        <div>D</div>
      </Fragment>
    </div>
  )
}
```

**Comment by russwyte** [comment] 2019-07-16 12:59
I have a function that works like this (this is from scala.js code that creates the vdom via preact):

```scala
  override def render(props: ReaderProps): Node =
    fragment(
      readerTool(props.readerState.width)(
        TitleBar(Some(TitleBar.Props(props.readerState))),
        ViewPort(props.readerState)
      ),
      DragHandle(props.readerState.eventHandlers.dragHandleMouseDown)
    )
```

fragment calls:
`Preact.h(Fragment, null, children: _*)`

What I see when I inspect the dom after inserting a new fragment is this:
![image](https://user-images.githubusercontent.com/356303/61296159-37d73480-a79f-11e9-9314-7050940a26ed.png)

Forgive me - but I am not sure how to reproduce this in codesandbox. I will see if I can.

One observation is that in my case both members of the fragment are themselves components.

**Comment by russwyte** [comment] 2019-07-16 13:40
When I console log the fragments the children are present and in the right order - but they are not rendered in the correct order.

**Comment by russwyte** [comment] 2019-07-16 14:08
When I simply my code to replicate the problem like this:
```scala
  override def render(props: ReaderProps): Node = {
    val f = fragment(
      E.div("A"),
      E.div("B")
//      readerTool(props.readerState.width, props.readerState.key)(
//        TitleBar(Some(TitleBar.Props(props.readerState))),
//        ViewPort(props.readerState)
//      ),
//      DragHandle(props.readerState.eventHandlers.dragHandleMouseDown)
    )
    log("frag", f.vn)
    f
  }
```

I see this:
![image](https://user-images.githubusercontent.com/356303/61301160-f9467780-a7a8-11e9-9c8f-13e186ebe484.png)

FWIW - all of the components in this app only take props (they are stateless). I use a redux like state and re-render the app whenever I am notifies the state has changed.

**Comment by marvinhagemeister** [comment] 2019-07-16 14:43
Thanks for diving deeper into this 👍 We really want to make sure that all `Fragment` related bugs are squashed.

The smaller example looks similar to the snippet above. I've tried various other scenarios, but without success in reproducing the described behaviour.

Are you sure that it's using the `rc.0` version? We had issues like that back in earlier betas. Is there any way you can and are allowed to share the repo? I'm happy to do it privately. We need some way to reproduce the issue to be able to fix it 🙂

**Comment by russwyte** [comment] 2019-07-16 16:08
No sweat - I love Preact - so I hope we can get to the bottom of this. 😃  I will see if I can create a minimal reproducing app that I can share.

For now I have worked around the problem by using divs instead of frags.

**Comment by russwyte** [comment] 2019-07-16 16:09
Oh and yes I am using rc0

```
npmDependencies in Compile ++= Seq(
      "preact"       -> "10.0.0-rc.0",
      "autoprefixer" -> "9.6.1"
    )
```

**Comment by russwyte** [comment] 2019-07-16 16:10
If it helps here is the library I wrote to create a scala.js facade for Preact - this is what my app is using:

https://github.com/russwyte/EarlyEffect

**Comment by ceigey** [comment] 2019-07-25 02:10
@russwyte I'm just a stranger strolling by*, but I was thinking it might be useful to look at what the JavaScript emitted by ScalaJS looks like.

(Having code in the same language as the library seems like it'd make debugging a little more straightforward, otherwise you have to make assumptions about ScalaJS. E.g. my naive intuition is that sometimes compile-to-JS languages like Reason handle types very differently to what the host language (JavaScript) expects, e.g. Ocaml lists can cause amusing bugs for JS interop).

Also, cool to see Scala + Preact. All I've done before is use preact/compat with ReasonReact :sweat_smile:  

*just reading the issues to see if there's anything critical that would prevent adoption of Preact for my teammates

**Comment by JoviDeCroock** [comment] 2020-01-16 23:50
This should be fixed in stable, feel free to reopen if this is not the case

**Closed by JoviDeCroock** 2020-01-16 23:50 UTC
Labels: needs-more-info
