### ISSUE TITLE
ReactCurrentOwner Simulate

### ISSUE THREAD

**Issue by Aloento** [preactjs/preact#3809] opened 2022-11-20 23:08 UTC
```js
const internal = React.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED;
internal.ReactCurrentOwner = { current: null } // vnode
```

Because Preact doesn't have such things, `excalidraw` can't be used in preact
is there a way to simulate them?

https://github.com/preactjs/preact/pull/3424

**Comment by marvinhagemeister** [comment] 2022-11-21 06:25
Took a look into this and the problem is that their npm package `@excalidraw/excalidraw` ships with a partial copy of React. Both `react/jsx-runtime` and `react-dom/client` are inlined into the excalidraw package. Mixing partial copies of React with Preact is not supported. So the issue isn't about us not setting `ReactCurrentOwner` correctly, but rather the mixing of React and Preact internals.

Your analysis in https://github.com/excalidraw/excalidraw/issues/5909 is spot on.

Closing as this is an upstream issue and not an issue in Preact.

**Closed by marvinhagemeister** 2022-11-21 06:25 UTC
Labels: feature request

**Comment by imvetri** [comment] 2023-11-20 16:42
Why react errors are mixed with preact ?  

CC @marvinhagemeister
