### ISSUE TITLE
[10.0.0-rc1] Really weird issue with react-redux connect()

### ISSUE THREAD

**Issue by mzealey** [preactjs/preact#1864] opened 2019-08-13 13:44 UTC
So I'm running slightly newer than -rc1 based on the git from ~18h ago. Running with a particular route under react-router-dom with a route like `/foo/:id` I have a relatively simple component which is connected to the store with react-redux and toggles between `null` and a sub-component view based on the value from the store - in test case below the string `foo`. When the id value changes a different prop (`song`) is passed to the subcomponent. The bug is that when the component is showing on a page and the store changes to make `render()` return null, the component hides correctly. But when I navigate to a new id (ie doesnt unmount, but props change) the component is rendered in its old form even though `render()` is still called and returns null.

If I switch away from using the `connect()` function to directly subscribing and changing component state based on the store value then the component behaves correctly. Switching to react 16.9.0 also does not display this issue.

Smallest case I can reproduce with in my app (ie inside the routing) is below. This is the one that doesn't work:

```
class _PresenterView extends Component {
    render() {
        const { song, is_active } = this.props;

        if( !is_active )
            return null;
    
        return 'foo';
    }
}
export const PresenterView = connect(state => ({ is_active: state.cast.active }))(_PresenterView);
```

And if we connect manually to the store then this works correctly:

```
export class PresenterView extends Component {
    componentDidMount() {
        store.subscribe(() => this.setState({ is_active: store.getState().cast.active }));
    }

    render() {
        const { is_active } = this.state;
        const { song } = this.props;

        if( !is_active )
            return null;
    
        return 'foo';
    }
}
```

**Comment by JoviDeCroock** [comment] 2019-08-13 14:56
What versions  are you running from the sub-libraries, it would probably help to make a minimal codesandbox. This ensures that we aren't looking at an issue with another library introducing an issue.

**Comment by mzealey** [comment] 2019-08-13 18:08
OK I have isolated this to some extent... https://codesandbox.io/s/issue-1864-l22yq - click 'toggle visibility' to show the counter, then click 'increment' - should show 2. Then click 'toggle visibility' to hide the element. Then clicking the 'increment' again shows 2 even though the bit is hidden (ie returns null). Clicking toggle visibility button again nows shows 2 counters the legacy bit of dom and the up-to-date version which should read 3. It appears to be triggered by the `Promise.then` line.

**Comment by JoviDeCroock** [comment] 2019-08-13 18:22
Your sandbox is using the wrong compat layer, it's using `preact-compat` which is not correct for Preact X

**Comment by marvinhagemeister** [comment] 2019-08-13 18:24
Our upgrade guide has a section for that: https://preactjs.com/guide/v10/upgrade-guide#compat-has-moved-to-core

**Comment by mzealey** [comment] 2019-08-13 18:34
hm not sure how to set up aliases on that platform. I am seeing the same issue locally with webpack aliasing react / react-dom to preact/compat and I don't have any preact-compat in my node_modules so pretty sure it's not due to this dep issue.

**Comment by JoviDeCroock** [comment] 2019-08-13 18:36
Nope, I see your issue. It's probably the way `react-redux` schedules their updates

**Comment by JoviDeCroock** [comment] 2019-08-13 19:22
@mzealey why are you using that Promise.resolve?

**Comment by mzealey** [comment] 2019-08-13 19:33
In my code I have a promise chain which appears to be causing/triggering the issue. This was an easy way to trigger the same behaviour in minimal test case... I have not seen this issue in standard react so seems to be an issue with preact interaction with react-redux.On 13 Aug 2019 22:22, Jovi De Croock <notifications@github.com> wrote:@mzealey why are you using that Promise.resolve?

**Comment by JoviDeCroock** [comment] 2019-08-13 21:05
What is the promise for? Is it component-level or something achieved somewhere else, if it's component level and you are trying to achieve incremental state updates you can use the callback of your first setState

**Comment by mzealey** [comment] 2019-08-14 09:25
In production it's more like `.then(do something).finally(hide spinner)` type so i can obviously rewrite it to some extent but it still seems to be a bug in preact :)

**Comment by JoviDeCroock** [comment] 2019-08-14 09:36
I think this is mainly due to the way we schedule updates, I'll try and look deeper into this.

**Comment by mzealey** [comment] 2019-08-14 09:40
Sure, I'm guessing a `setTimeout()` type wrap hack might fix in this case too as it would appear to be a race of some sort

**Comment by JoviDeCroock** [comment] 2019-08-14 09:43
The thing is we schedule our setState with microtasks `Promise.resolve.then`, this probably conflicts as I see the `react-redux`, `react-router` and your first setState batched but then one that gets dispatched inside `diff` (?). As I said I'll look deeper into this after work.

**Comment by mzealey** [comment] 2019-08-14 09:45
btw `react-router` shouldnt be required for this I think I removed it from the test case

**Comment by marvinhagemeister** [comment] 2019-08-18 11:29
yup, it's not required. Found the root cause and the PR should be merged soon :+1:

**Comment by marvinhagemeister** [comment] 2019-08-18 16:31
Re-opening, looks like we missed a few cases.

**Comment by JoviDeCroock** [comment] 2020-01-16 23:47
This should be fixed in the stable version

**Closed** 2020-01-16 23:47 UTC
