### ISSUE TITLE
Strange animations with keys 

### ISSUE THREAD

**Issue by michaelkrukov** [preactjs/preact#1964] opened 2019-10-02 00:42 UTC
I was trying to get the library `https://github.com/STRML/react-grid-layout` to work with preact. I encountered an issue that preact misses animation on items inside of the grid (because of rerenders, I guess), and sometimes animates wrong items. For example, removing 0th item make all other items act like they were moved (on preact 8). 

React version: https://codesandbox.io/s/dreamy-matsumoto-k6778
Preact (8) version: https://codesandbox.io/s/strange-worker-9r59j

I couldn't setup codesandbox for Preact X, but I am having similar issues on my machine (but without wrong animations).

Is there a fundamental problem in the library? Can this be fixed?

**Comment by developit** [comment] 2019-10-02 01:51
Hi @michaelkrukov! Apologies for the confusion with our CodeSandbox template - we're still in the process of updating it to Preact 10.

Here's your demo using Preact 10.0.0 on codesandbox:
https://codesandbox.io/s/issue-1964-5mu06

It appears to be working correctly, but I'm not 100% sure I'm looking for the right thing.

**Comment by michaelkrukov** [comment] 2019-10-02 02:01
@developit, it should animate elements, that moves up to take free space. But in all cases animation happens only if removed item was added after ones beelow it. Looks like it defined by order in the list (and DOM).

**Comment by michaelkrukov** [comment] 2019-10-02 08:04
# Examples

## React
![react](https://user-images.githubusercontent.com/13236694/66027711-27b03500-e504-11e9-97d5-4b4807af8408.gif)

## Preact 8
![preact8](https://user-images.githubusercontent.com/13236694/66027710-27179e80-e504-11e9-98ba-0761c244c13b.gif)

## Preact X
![preact10](https://user-images.githubusercontent.com/13236694/66027709-27179e80-e504-11e9-9ea2-bb47297e6f42.gif)

**Comment by michaelkrukov** [comment] 2019-10-03 03:35
So, after digging into the [library source](draggableCancel), I fount out that children of ReactGridLayout (they have the key prop) wrapped in `GridItem`, that don't have a key prop. Adding key to wrapper seems to cure this issue. 

It looks like react uses the child's child's key to keep nodes, but preact doesn't do it. I'm not sure, how I will fix it, but this isn't `preact` issue (i guess?), so it can be closed.

**Comment by developit** [comment] 2019-10-05 01:07
Hmm - that's a behaviour I'm unfamiliar with @michaelkrukov. If Preact is doing something dramatically different then it may be worth seeing if we can reconcile.

**Comment by kish0022** [comment] 2020-03-13 12:26
Same issue with the react-bootstrap - carousel. 
Using react-bootstrap carousel module in preact and slide animation is working perfect on dev start but not with build.

Is there any one have working example ? Thanks

**Comment by marvinhagemeister** [comment] 2020-03-13 16:48
@kish0022 Can you open a new issue for that? Just checked the sandboxes in the original issue description and it has been fixed in a past release.

Closing because I can't reproduce the issue of the original poster with the lastest version of Preact anymore.

**Closed by marvinhagemeister** 2020-03-13 16:48 UTC
Labels: compat, discussion, question
