### ISSUE TITLE
[QUESTION] How to avoid hydration for static content

### ISSUE THREAD

**Issue by aralroca** [preactjs/preact#2364] opened 2020-02-23 17:59 UTC
We recently switched from React to Preact and one of the things that we miss in performance is that with React we had a hack to avoid Hydration for static content.

I had this code (Suggested on https://github.com/facebook/react/issues/10923#issuecomment-338715787):

```html
<StaticContent><MyStaticComponent /></StaticContent>
```

```js
import { createElement, useRef, useState, useEffect } from 'react'

function useStaticContent() {
  const ref = useRef(null)
  const [render, setRender] = useState(typeof window === 'undefined')

  useEffect(() => {
    // check if the innerHTML is empty as client side navigation
    // need to render the component without server-side backup
    const isEmpty = ref.current.innerHTML === ''
    if (isEmpty) {
      setRender(true)
    }
  }, [])

  return [render, ref]
}

export default function StaticContent({ children, element = 'div', ...props }) {
  const [render, ref] = useStaticContent()

  // if we're in the server or a spa navigation, just render it
  if (render) {
    return createElement(element, {
      ...props,
      children,
    })
  }

  // avoid re-render on the client
  return createElement(element, {
    ...props,
    ref,
    suppressHydrationWarning: true,
    dangerouslySetInnerHTML: { __html: '' },
  })
}
```

However, in Preact this hack is not avoiding the hydration... Is there another way to do it? 👏

**Comment by developit** [comment] 2020-02-24 16:19
Hi! This should work in Preact - looks like we had an issue with our compat layer that @JoviDeCroock's PR addresses.

FWIW we're using this exact `dangerouslySetInnerHTML` hydration bypass trick on preactjs.com 👍

**Comment by JoviDeCroock** [comment] 2020-02-25 14:16
Hey @aralroca

This will be fixed in the next release, thanks for the awesome issue report, it really helps us with rapidly fixing issues like these.

I’m going to close this issue now, feel free to reopen if there’s anything wrong with it.

**Closed by JoviDeCroock** 2020-02-25 14:16 UTC
Labels: compat, has fix

**Comment by aralroca** [comment] 2020-02-25 14:36
Thank you @JoviDeCroock and @developit ! I just reported yesterday and today is already fixed! This is incredible and I feel very happy with the change to Preact ecosystem.

**Comment by aralroca** [comment] 2020-03-07 17:03
> feel free to reopen if there’s anything wrong with it.

@JoviDeCroock adding this check to the test that you did, the test is failing. Is this as you expect?

```diff
	it('should support static content', () => {
		const updateSpy = sinon.spy();
		const mountSpy = sinon.spy();
		const renderSpy = sinon.spy();
+		const eventSpy = sinon.spy();

		function StaticContent({ children, element = 'div', staticMode }) {
			// if we're in the server or a spa navigation, just render it
			if (!staticMode) {
				return createElement(element, {
					children
				});
			}

			// avoid re-render on the client
			return createElement(element, {
				dangerouslySetInnerHTML: { __html: '' }
			});
		}

		class App extends Component {
			componentDidMount() {
				mountSpy();
			}

			componentDidUpdate() {
				updateSpy();
			}

			render() {
				renderSpy();
+				return <div onClick={() => eventSpy()}>Staticness</div>;
			}
		}

		act(() => {
			render(
				<StaticContent staticMode={false}>
					<App />
				</StaticContent>,
				scratch
			);
		});

		expect(scratch.innerHTML).to.eq('<div><div>Staticness</div></div>');
		expect(renderSpy).to.be.calledOnce;
		expect(mountSpy).to.be.calledOnce;
		expect(updateSpy).to.not.be.calledOnce;

		act(() => {
			hydrate(
				<StaticContent staticMode>
					<App />
				</StaticContent>,
				scratch
			);
		});

		expect(scratch.innerHTML).to.eq('<div><div>Staticness</div></div>');
		expect(renderSpy).to.be.calledOnce;
		expect(mountSpy).to.be.calledOnce;
		expect(updateSpy).to.not.be.calledOnce;
+		scratch.firstChild.firstChild.dispatchEvent(new Event('click'))
+		expect(eventSpy).to.not.be.calledOnce;
	});
});
``` 

I can reopen it... 😅

**Comment by JoviDeCroock** [comment] 2020-03-07 21:32
That would be magic if React would add that since you set it as dangerouslySetInnerHTML which isn’t diffed

**Comment by aralroca** [comment] 2020-03-07 22:42
@JoviDeCroock Maybe I didn't express myself correctly. I wanted to say that in a normal hydration (not this example) the events are attached during the hydration, as react do. However, avoiding the hydration with this hack, I was expecting that the events are not attached... And they are attached as the failing example shows.

**Comment by JoviDeCroock** [comment] 2020-03-08 14:22
Hmm in a real SSR scenario this shouldn't happen but yes I can see why this happens in this test, I'll see if I can do something about it

**Comment by Nandan1996** [comment] 2020-11-26 17:15
@JoviDeCroock is there any way to avoid hydration for static content in older version of preact 8.1.0?

**Comment by developit** [comment] 2020-12-02 02:46
@Nandan1996 the `dangerouslySetInnerHTML` hack works in Preact 8. Best to upgrade though.

**Comment by Nandan1996** [comment] 2020-12-02 03:00
> @Nandan1996 the `dangerouslySetInnerHTML` hack works in Preact 8. Best to upgrade though.

@developit Thank you for replying. I've tried this yesterday but the line at https://github.com/preactjs/preact/blob/17cc8deddd3d4e592685dfa42e832f6e8d2cb795/src/vdom/diff.js#L143 seems to remove static html injected using `dangerouslySetInnerHTML` during hydration. later it gets injected again that causes high `LCP` score in our case.

we're planning to revamp our product but till then we need a temp fix.

Thanks.

**Comment by dayvista** [comment] 2021-11-11 00:12
I believe I'm running into a similar issue - This hack doesn't work as expected in Preact compared to React.

I'm using the `dangerouslySetInnerHTML` hack with Next.js and the [`next/dynamic` package](https://nextjs.org/docs/advanced-features/dynamic-import#with-custom-loading-component). When a component hydrates, the HTML rendered on the server is fetched using `getDocumentById` and passed to `next/dynamic`'s `loading` prop as the loader component - thus preventing layout shift/flickering during hydration.

It works using React but breaks using Preact - the `getDocumentById` call now returns `null` during the hydration phase. I suspect this is because the static HTML gets removed per @Nandan1996's comment. Is there any way to preserve the HTML until the component is properly hydrated?

[Here's a reproduction](https://stackblitz.com/edit/nextjs-mwqhkg?devtoolsheight=33&file=next.config.js). Head to the `next.config.js` file and un-comment lines 48 - 57 (this switches Next.js from using React to Preact) then restart the dev server to see what I'm talking about.

**Comment by dayvista** [comment] 2021-11-11 23:52
Figured out a workaround:
1. Immediately before hydration, grab `outerHTML` of un-hydrated component and place in global state - I'm using [zustand](https://github.com/pmndrs/zustand)
2. Hydrate while using stored HTML as fallback/loading component - I'm using [htmr](https://github.com/pveyes/htmr)
3. Delete HTML from store immediately after hydration because it's no longer needed
