### ISSUE TITLE
Cannot find name 'SVGMPathElement'

### ISSUE THREAD

**Issue by sivakg2000** [preactjs/preact#3918] opened 2023-02-27 14:16 UTC
- [ ] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
Getting the below exception,

`Error: node_modules/preact/src/jsx.d.ts:2138:24 - error TS2304: Cannot find name 'SVGMPathElement'.

2138   mpath: SVGAttributes<SVGMPathElement>;
                            ~~~~~~~~~~~~~~~


Error: node_modules/preact/src/jsx.d.ts:2145:22 - error TS2304: Cannot find name 'SVGSetElement'.

2145   set: SVGAttributes<SVGSetElement>;`

**To Reproduce**
 

If possible, please provide a CodeSandbox/Codepen that demonstrates the issue. You can use the following template: https://codesandbox.io/s/preact-x-preact-cli-3-starter-vj285y2rn3

Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. See error

**Expected behavior**
What should have happened when following the steps above?

**Comment by rschristian** [comment] 2023-02-28 01:42
This was fixed in #3905 and released in version `10.13.0`. Please update your Preact version to get access to these improved types.

In the future, please fill in the issue template. It's there to help us help you.

**Closed by rschristian** 2023-02-28 01:42 UTC

**Comment by sivakg2000** [comment] 2023-02-28 05:10
@rschristian, Thanks, But this is coming from 10.13.0 only. I'm not using directly preact, Using "@fullcalendar/angular": "^5.11.4",  I'm getting the issue while compiling, This is coming recently.

**Comment by rschristian** [comment] 2023-02-28 05:14
Please create a minimal reproduction please (you can find a starter in the issue template) as I cannot reproduce any type error in v10.13.0

**Comment by EliezerB123** [comment] 2023-02-28 12:01
Note that `Angular <13` does not support `typescript v4.4.0`, for any other people that come looking.
