### ISSUE TITLE
Typescript error 'ComponentChildren' is not assignable to type 'ReactNode'.

### ISSUE THREAD

**Issue by selankon** [preactjs/preact#3900] opened 2023-02-16 08:32 UTC
- [X] Check if updating to the latest Preact version resolves the issue

**Describe the bug**

We are trying to migrate our app to Typescript but with a simple component  like this I got an error:

> TS2322: Type 'ComponentChildren' is not assignable to type 'ReactNode'.   Type 'bigint' is not assignable to type 'ReactNode'.

```ts
export const SectionTitle = ({ children }: {children: ComponentChildren}) => {
    return (
        <div>
            {children}
        </div>
    );
};
```

**To Reproduce**

The app contain multiple packages and I guess one of them is causing the error. I write the issue here because I'm pretty sure is related to this one: https://github.com/preactjs/preact/issues/2748

It compiles using Babel, and has multiple packages, one of them probably uses the react types which are conflicting with the preact ones(???)

Clone the fork im working on and run `npm install`:

```
git clone -b f/implement_new_landing https://github.com/selankon/lime-app/
```

Then run tsc to see the errors over the file I'm working on:

```
tsc plugins/lime-plugin-rx/src/components/components.tsx
```

**Expected behavior**

This shouldn't have any errors, but instead I got this one described above.

I followed the instructions on preact docs https://preactjs.com/guide/v10/typescript/#typescript-configuration configuring babel and TS with this options:

* babel-config.js

```
module.exports = {
    presets: [
        "@babel/preset-env",
        ["@babel/typescript", { jsxPragma: "h" }],
        "@lingui/babel-preset-react",
        "preact",
    ],
    plugins: [
        "macros",
        [
            "@babel/plugin-transform-react-jsx",
            {
                pragma: "h",
                pragmaFrag: "Fragment",
            },
        ],
        [
            "babel-plugin-jsx-pragmatic",
            {
                module: "preact",
                import: "h",
                export: "h",
            },
        ],
    ],
};
```

* tsconfig.json

```
/* Module Resolution Options */
    "moduleResolution": "Node",
    "esModuleInterop": true,
    /* Advanced Options */
    "skipLibCheck": true,
    "baseUrl": "./",
    "paths": {
      "react": ["./node_modules/preact/compat/"],
      "react-dom": ["./node_modules/preact/compat/"],
```

Without success. 

I'm working on a simplier error but for the moment I didn't reproduced the error. As I said, probably a dependency is causing the conflict. Any help is welcome, I will update here if can help to anyone on the future. 

Thanks

**Comment by selankon** [comment] 2023-02-17 07:39
Ok I found who is depending on `@types/react`:

```
npm ls @types/react
preact-limeapp@0.2.25 /home/user/src/libremesh/lime-app
└─┬ react-redux@8.0.4
  ├─┬ @types/hoist-non-react-statics@3.3.1
  │ └── @types/react@18.0.26 deduped
  └── @types/react@18.0.26
```

So I created a minimum reproducible example project: 

https://github.com/selankon/preact-types-error-example

Just do `yarn` and then check types validation:

```bash
➜ tsc --jsx react-jsx src/app.tsx
src/app.tsx:6:13 - error TS2322: Type 'ComponentChildren' is not assignable to type 'ReactNode'.
  Type 'bigint' is not assignable to type 'ReactNode'.

6             {children}
              ~~~~~~~~~~
```

**Comment by selankon** [comment] 2023-02-17 08:11
Either, using the component described on the first comment and without installing the `@types/react` module, I got this error doing this:

```ts
<SectionTitle>{"Hello World"}</SectionTitle>
```

> Property 'children' is missing in type '{}' but required in type 'SectionTitleProps'.

Although the error is gone on the `SectionTitle` component, I can't pass the children property without doing  `<SectionTitle children={"HelloWorld"} />`.

**Comment by selankon** [comment] 2023-04-06 06:42
Could somebody give me a push of where to search? Thanks!

**Comment by rschristian** [comment] 2023-04-14 20:40
Sorry for the delay.

It looks like you've misconfigured TypeScript. When you set `--jsx react-jsx`, TS will default to React as the JSX runtime import source. You need to specify Preact by adding `--jsxImportSource preact`.

[TSConfig Docs](https://www.typescriptlang.org/tsconfig#jsxImportSource)
[Preact Docs](https://preactjs.com/guide/v10/typescript#typescript-configuration)

However, if you're using `preact-cli`, you should not be setting `react-jsx`, as it does not use the runtime transform in v3. It uses the classic, which the `tsconfig.json` is already correctly configured for.

Not really relevant to the issue, but if you are using `preact-cli`, please remove all those Babel plugins. It's entirely unnecessary, it transforms JSX and TS for you.

---

React, as of v18, made their types much stricter when it comes to what can or cannot be a `ReactNode`, and that's the error you're seeing. You shouldn't see it if you're using Preact's types, but as there are situations in which that might not be ideal, you may simply need to use v17 of React's types or fix your usage.

**Comment by selankon** [comment] 2023-04-20 08:55
Thanks for your indications, after some modifications I can use `ComponentChildren` as `ReactNode`. My tsconfig.json looks like: 

```json
 "compilerOptions": {
      /* Basic Options */
      "target": "ES5",
//      "module": "ESNext",
      "allowJs": true,
      "checkJs": true,
      "jsx": "react-jsx",
//      "jsxFactory": "h",
//      "jsxFragmentFactory": "Fragment",
      "jsxImportSource": "preact",
      "noEmit": true,

      /* Strict Type-Checking Options */
      "strict": false,

      /* Module Resolution Options */
      "moduleResolution": "node",
      "esModuleInterop": true,
      "baseUrl": "./",
      "paths": {
          "react/*": ["./node_modules/preact/compat/*"],
          "react-dom/*": ["./node_modules/preact/compat/*"],
          "components/*": ["./src/components/*"],
          "containers/*": ["./src/containers/*"],
          "utils/*": ["./src/utils/*"],
          "plugins/*": ["./plugins/*"]
      },
      "allowSyntheticDefaultImports": true,

      /* Advanced Options */
      "skipLibCheck": true
  },
  "include": ["plugins/**/*", "src/**/*", "stories/**/*"],
  "exclude": [
    "node_modules/**/*",
    "build/**/*",
    "**/*.spec.js",
    "**/*.stories.js"
  ]
  ```

I also deleted babel dependencies, which is causing a lingui package problem that I guess is not related to here. 

The POC: https://github.com/selankon/lime-app/commit/98c0a2d16c1f260d4b21d63b8db71df295a20c77

Also I detected that adding typescript to the app it increase on 200KB the build bundle. Opened new issue https://github.com/preactjs/preact/issues/3975

**Comment by rschristian** [comment] 2023-04-20 10:01
Looks like you missed this part of my comment:

> However, if you're using preact-cli, you should not be setting react-jsx, as it does not use the runtime transform in v3. It uses the classic, which the tsconfig.json is already correctly configured for.

But sounds like the issue was resolved, so I'll close this out.

**Closed by rschristian** 2023-04-20 10:01 UTC
Labels: types

**Comment by selankon** [comment] 2023-04-24 08:52
Ok, I am not understanding some parts, because i am using preact-cli instead of using  `react-jsx` I have to use this config:

```json
      "jsx": "preserve",
      "jsxFactory": "h",
      "jsxFragmentFactory": "Fragment",
      "jsxImportSource": "preact",
 ```
 
 Which is little confusing for me with the [docs](https://preactjs.com/guide/v10/typescript#typescript-configuration) that say that this config is for `TypeScript < 4.1.1` (and I am using `4.9.4`). Anyway with `preact watch` this works properly. 

On the other hand:

> Not really relevant to the issue, but if you are using preact-cli, please remove all those Babel plugins. It's entirely unnecessary, it transforms JSX and TS for you.

So, after I deleted al babel deps, and either deleted the configs from webpack etc... And I got a bunch of this errors when running `lingui extract; lingui compile`: 

```
Cannot process file Cannot find module 'babel-preset-preact'
Require stack:
- path/lime-app/node_modules/@babel/core/lib/config/files/plugins.js
- path/lime-app/node_modules/@babel/core/lib/config/files/index.js
- path/lime-app/node_modules/@babel/core/lib/index.js
- path/lime-app/node_modules/@lingui/cli/api/extractors/babel.js
- path/lime-app/node_modules/@lingui/cli/api/extractors/index.js
- path/lime-app/node_modules/@lingui/cli/api/catalog.js
- path/lime-app/node_modules/@lingui/cli/lingui-extract.js
- If you want to resolve "preact", use "module:preact"
``` 

I am not sure why this error is shown, and I guess is working anyway. But, to make it disappear I had to install:

```bash
npm i -D babel-preset-preact @lingui/babel-preset-react
``` 

Not sure if I can avoid this deps using some additional config. 

Thanks

**Comment by selankon** [comment] 2023-04-24 09:26
Thanks for answering so fast, all clear now :+1:

**Comment by selankon** [comment] 2023-04-28 08:45
FTR

After disable babel dependencies I got jest error: 

> Support for the experimental syntax 'jsx' isn't currently enabled

And looking on [internet](https://stackoverflow.com/questions/62820035/babel-throwing-support-for-the-experimental-syntax-jsx-isnt-currently-enabled) I saw that I have to modify the jest config to use `ts-jest`. 

But doing the changes makes deprecated all the existent JS tests with lots of errors like: 

```
 Property 'mockImplementation' does not exist on type '() => Promise<any>'.
```

The solution for this is to mock properly the objects. But for the moment I just restored babel and opened an issue to do it on the future.

**Comment by selankon** [comment] 2023-04-28 09:14
Thanks again for answering so fast. 

I already have `jest-preset-preact` installed. And I disabled the `jest.config.js` option:

```diff
-    transform: {
-        "^.+\\.[tj]sx?$": "babel-jest",
-    },
```

Then after running `npm run test` I got this error: 

> ReferenceError: h is not defined

I guess babel was doing something there, I don't know what it did and how to replace it `preact-cli` (I am pretty new at this world...). 

Thanks for help

**Comment by rschristian** [comment] 2023-04-28 10:22
>>  ReferenceError: h is not defined
>
> I guess babel was doing something there,

Ah, you're not importing `h` into your components, but relying upon a Babel plugin to inject `h` into them? You can add that back in, but you'd want to limit it to your tests, as shown here: https://stackoverflow.com/a/35462890/15388164

[Preact-CLI supports that natively through Webpack](https://github.com/preactjs/preact-cli/blob/8d65d945059c569f81288c445ec9868b2a71a5df/packages/cli/src/lib/webpack/webpack-base-config.js#L329-L332), though in all honesty few take advantage as TypeScript tends to not like this... Anyways, you'd want to avoid duplicating the functionality (when running build/dev) by limiting your Babel config (or this specific portion of it) to tests only.

**Comment by GongT** [comment] 2023-07-18 11:37
modify `@types/react`

```patch
diff --git a/index.d.ts b/index.d.ts
index bb1df3736f848756c6ea6ca05825610059cc9fc7..0f1c481875ce155efaa95179fd2e57d465ad3e81 100755
--- a/index.d.ts
+++ b/index.d.ts
@@ -255,6 +255,7 @@ declare namespace React {
      */
     interface DO_NOT_USE_OR_YOU_WILL_BE_FIRED_EXPERIMENTAL_REACT_NODES {}
     type ReactNode =
+		| import('preact').ComponentChild
         | ReactElement
         | string
         | number
@@ -402,8 +403,8 @@ declare namespace React {
     type Provider<T> = ProviderExoticComponent<ProviderProps<T>>;
     type Consumer<T> = ExoticComponent<ConsumerProps<T>>;
     interface Context<T> {
-        Provider: Provider<T>;
-        Consumer: Consumer<T>;
+        Provider: any; // Provider<T>;
+        Consumer: any; // Consumer<T>;
         displayName?: string | undefined;
     }
     function createContext<T>(
```

**Comment by GongT** [comment] 2023-07-18 11:58
I think this issue still exists.

https://codesandbox.io/p/sandbox/relaxed-lichterman-49j3n9

**Comment by rschristian** [comment] 2023-07-18 23:56
@GongT That example appears to have the TS path aliases commented out, which means you're using React's types, not ours.

**Comment by GongT** [comment] 2023-07-20 16:34
@rschristian `paths` is only for project files, no effect inside node_modules. In this case, I use `import 'preact'` in my code.

The problem is there are many "import 'react'" in 3rd-party libraries (`primereact` in my case), which cause conflict.

**Comment by rschristian** [comment] 2023-07-20 16:38
> @rschristian `paths` is only for project files, no effect inside node_modules. In this case, I use `import 'preact'` in my code.

This is incorrect, it absolutely will affect type resolution inside `node_modules`, hence why we recommend it.

There still is plenty of surface area for issues (missing or incompatible types in Preact) but please re-enable that setting, it does have an affect.

**Comment by GongT** [comment] 2023-07-20 16:44
But it still not compile after enable this setting. 😢 

Do you know which project uses preact without any build tools? I think I need some examples.

**Comment by rschristian** [comment] 2023-07-20 23:55
> But it still not compile after enable this setting. 😢

Hmm, your example looks to be fine to me? Admittedly, it looks like the `<Button>` component from that library you're using accepts any props... not sure if that's correct or not.

> Do you know which project uses preact without any build tools? I think I need some examples.
>
> (To clarify, I use esbuild, but I also need tsc to create the declaration files, so I can't just let esbuild do everything)

Are you looking for apps or libraries? "without any build tools" usually means apps & not caring about `.d.ts` gen, so this is a bit unclear.

**Comment by rschristian** [comment] 2023-07-21 00:42
Here's a dead-simple example of using `"paths"` aliases to correct types from `node_modules`: https://github.com/rschristian/simple-react-lib-in-preact-with-typescript

Just clone and open in your editor, no need to install.

With `"paths"` in the `tsconfig.json` commented out, you'll see no errors in `src/index.tsx`, as TypeScript isn't able to resolve `react` in `react-lib`'s types to accurately type-check against. If you uncomment it, now `react` in `react-lib`'s types resolves to `preact/compat` and you get accurate types returned (an error, in this case, as I added an invalid prop in `src/index.tsx`).
