### ISSUE TITLE
preact/debug breaks on preact/devtools import

### ISSUE THREAD

**Issue by brion-fuller** [preactjs/preact#2867] opened 2020-12-14 12:38 UTC
### Reproduction

https://codesandbox.io/s/preactdebug-esm-7165v?file=/index.html

### Steps to reproduce

Using the link above, you can see that nothing is rendered on the page.
The error message that I get is a 404 on `https://unpkg.com/preact@10.5.7/devtools?module`.
I believe this is because of trying to use scope like naming without scoping.  So preact/devtools instead of @preact/devtools.  unpkg is picking this up as a path name instead and not reading from the package.json.

### Expected Behavior

`https://unpkg.com/preact/devtools` should resolve to `https://unpkg.com/preact@10.5.7/devtools/dist/devtools.module.js?module`

### Actual Behavior

`https://unpkg.com/preact/devtools` resolves to `https://unpkg.com/preact@10.5.7/devtools?module`

**Comment by marvinhagemeister** [comment] 2020-12-14 13:36
This is a known error in the module resolution code of `unpkg`. This can't be fixed on our end.

See:
- https://github.com/mjackson/unpkg/issues/281
- https://github.com/mjackson/unpkg/issues/129
- https://github.com/preactjs/preact/issues/2564

The recommended solution is to use a CDN which supports ES Module resolution, like https://npm.reversehttp.com/

```jsx
// preact and preact/hooks: 10.5.7, and htm/preact: 3.x.x:
import { html, render } from 'npm.reversehttp.com/preact@10.5.7,preact@10.5.7/hooks,htm@3/preact';
```

Closing, because this is a duplicate of #2564 and we can't solve it on our end.

**Closed by marvinhagemeister** 2020-12-14 13:36 UTC
