### ISSUE TITLE
v10.0.0-rc.0 invalid WeakMap key in devtools

### ISSUE THREAD

**Issue by droganov** [preactjs/preact#1772] opened 2019-07-12 16:47 UTC
I've added this to webpack config:

```
resolve: {
    alias: {
      react: 'preact/compat',
      'react-dom': 'preact/compat',
      'create-react-class': 'preact/compat/lib/create-react-class',
      'react-dom-factories': 'preact/compat/lib/react-dom-factories',
    },
  },
```

Local build works. Publish to now worked, but SSR fails.
Now logs contain:
```
module initialization error: Error
You can add this by using "npm install --save preact-render-to-string@next".
    at Object.aDp2 (/var/task/page.js:46:22061)
    at __webpack_require__ (/var/task/page.js:1:339)
```

I've installed "preact-render-to-string": "^5.0.5" , and now it fails to render with

```
2019-07-12T16:44:54.626Z	bb6cddad-96f4-41f8-a086-71d3096fc8bb	TypeError: Invalid value used as weak map key
                              at WeakMap.set (native)
```

**Comment by marvinhagemeister** [comment] 2019-07-13 05:13
Looks like the devtools receive an invalid instance for a `vnode`. They are used to track them across renders. Any chance you could provide a snippet of your component structure or even better a reproduction case? As a quick workaround you can remove the `preact/debug` import.

Unrelated: The `create-react-class` and `react-dom-factories` alias can be removed. These were only necessary for compatibility with React versions <= 14.

**Comment by droganov** [comment] 2019-07-15 18:10
@marvinhagemeister
Here it is: https://github.com/droganov/preact-exlab

**Comment by marvinhagemeister** [comment] 2019-07-15 18:45
@droganov Awesome, thanks a bunch for the repo :+1: Note that I had to import them manually as that seems to be missing from the repo by putting this snippet into `index.jsx`.

Here is what I did:

1. run `npm start`
2. open devtools
3. click & inspect every element

**Comment by droganov** [comment] 2019-07-15 19:23
@marvinhagemeister ok, but it worked locally, the issue only occurs during serverless deploy to now cloud

please change project name in `now.json` and then try running `yarn build` (you need now login to do that)

Deployment fails and `now logs ...` brings:
```
2019-07-15T19:19:59.510Z  Compiled with warnings.
                          
                          ./node_modules/preact/compat/server.js
                          Module not found: Can't resolve 'preact-render-to-string' in '/tmp/5cb9a59a/node_modules/preact/compat'
2019-07-15T19:19:59.510Z  
2019-07-15T19:19:59.575Z  > Build error occurred
2019-07-15T19:19:59.576Z  Error: You seem to be missing the "preact-render-to-string" dependency.
                          You can add this by using "npm install --save preact-render-to-string@next".
                              at Object.aDp2 (/tmp/5cb9a59a/.next/serverless/pages/index.js:6907:8)
                              at __webpack_require__ (/tmp/5cb9a59a/.next/serverless/pages/index.js:23:31)
                              at Object.R+7f (/tmp/5cb9a59a/.next/serverless/pages/index.js:4632:18)
                              at __webpack_require__ (/tmp/5cb9a59a/.next/serverless/pages/index.js:23:31)
                              at Module.ILaR (/tmp/5cb9a59a/.next/serverless/pages/index.js:2808:14)
                              at __webpack_require__ (/tmp/5cb9a59a/.next/serverless/pages/index.js:23:31)
                              at /tmp/5cb9a59a/.next/serverless/pages/index.js:91:18
                              at Object.<anonymous> (/tmp/5cb9a59a/.next/serverless/pages/index.js:94:10)
                              at Module._compile (module.js:652:30)
                              at Object.Module._extensions..js (module.js:663:10)
```

**Comment by droganov** [comment] 2019-07-15 19:27
Actually after adding `preact-render-to-string@next` it started, but it looks strange to require `require("preact/debug")` in production

**Comment by marvinhagemeister** [comment] 2019-07-15 21:59
Agree the `preact/debug` import should not be used during production. It only includes helpful debug warnings and the devtools adapter. The typical way to do it is to wrap it with an environment check:

```js
if (process.env.NODE_ENV === 'development') {
  require('preact/debug');
}
```

**Comment by marvinhagemeister** [comment] 2019-07-16 06:31
Closing, because the issue seems to be fixed for the OP. Please ping us if you run into this again :slightly_smiling_face:

**Closed by marvinhagemeister** 2019-07-16 06:31 UTC
Labels: needs-more-info
