### ISSUE TITLE
When passing a component to a library package: “Hook can only be invoked from render methods”

### ISSUE THREAD

**Issue by rauschma** [preactjs/preact#3229] opened 2021-07-17 12:05 UTC
I’ve read everything I could find on the issue, tried various workarounds, but nothing worked. That may be because my setup is slightly unusual (but the repro project is simple).

As an aside, I’m getting the same error if I try this with React.

Repositories for reproducing the problem:

* https://github.com/rauschma/preact-repro-lib
* https://github.com/rauschma/preact-repro-app

`preact-repro-lib/ts/index.tsx`:

```ts
import { VNode } from 'preact';
import render from 'preact-render-to-string';

export type SimpleView = () => VNode;

export function logRenderedView(View: SimpleView) {
  console.log('----------');
  console.log(render(<View/>));
  console.log('----------');
}
```

`preact-repro-app/ts/main.tsx`:

```ts
import { logRenderedView } from 'preact-repro-lib';
import { useState } from 'preact/hooks';

import 'preact/debug';

function MyComponent() {
  const [clickCount, setClickCount] = useState(0);
  return <div>
    <a href="" onClick={handleClick}>{clickCount}</a>
  </div>;

  function handleClick(event: MouseEvent) {
    event.preventDefault();
    setClickCount(clickCount+1);
  }
}

logRenderedView(MyComponent);
```

Output:

```
Error: Hook can only be invoked from render methods.
    at Object.n.__h (file:///Users/rauschma/tmp/preact-repro-app/node_modules/preact/debug/dist/debug.mjs:1:6090)
    at m (file:///Users/rauschma/tmp/preact-repro-app/node_modules/preact/hooks/dist/hooks.mjs:1:125)
    at p (file:///Users/rauschma/tmp/preact-repro-app/node_modules/preact/hooks/dist/hooks.mjs:1:280)
    at l (file:///Users/rauschma/tmp/preact-repro-app/node_modules/preact/hooks/dist/hooks.mjs:1:249)
    at Object.MyComponent (file:///Users/rauschma/tmp/preact-repro-app/dist/main.js:6:41)
    at x (file:///Users/rauschma/tmp/preact-repro-lib/node_modules/preact-render-to-string/dist/index.mjs:1:2257)
    at m (file:///Users/rauschma/tmp/preact-repro-lib/node_modules/preact-render-to-string/dist/index.mjs:1:1077)
    at logRenderedView (file:///Users/rauschma/tmp/preact-repro-lib/dist/index.js:5:17)
    at file:///Users/rauschma/tmp/preact-repro-app/dist/main.js:13:1
    at ModuleJob.run (node:internal/modules/esm/module_job:175:25)
```

**Comment by satya164** [comment] 2021-07-17 13:07
I'm wondering if 2 copies of the Preact are being included in the bundle.

**Comment by rauschma** [comment] 2021-07-17 13:38
> I'm wondering if 2 copies of Preact are being included in the bundle.

Nothing is bundled, it’s all Node.js.

**Comment by visualfanatic** [comment] 2021-07-17 13:59
Everything works if you also pass `render` from `preact-render-to-string` to `logRenderedView` along with `MyComponent` in your `preact-repro-app` code. Looks like some side-effect, probably because of [the `options` object](https://github.com/preactjs/preact-render-to-string/blob/master/src/index.js#L9) that is shared between `preact` and `preact-render-to-string`.

**Comment by rauschma** [comment] 2021-07-17 14:09
@visualfanatic Very helpful, thanks! A downside is that (AFAICT) this won’t work if `app` wants to pass a mix of components with hooks to `lib` (some from `app`, some from `lib`).

**Comment by satya164** [comment] 2021-07-17 15:27
> Nothing is bundled, it’s all Node.js.

@rauschma maybe included in the bundle isn't the right word, in this case, more like 2 copies are being run and they don't share internal state between them.

**Comment by marvinhagemeister** [comment] 2021-07-17 16:54
@satya164 You have the right intuition. The issue is caused by loading 2 different copies of Preact. Both packages load their own instance of Preact. This happens because `preact-repo-app` loads `preact/hooks` and that in turn imports `preact`. The other package `preact-repo-lib` imports `preact-render-to-string` which loads `preact`.

This can be verified by checking both `node_modules` folders and placing some logging statements in the preact files.

**Comment by rauschma** [comment] 2021-07-17 17:32
Thanks @marvinhagemeister! Alas, bundling doesn’t seem to fix the problem, either (I tried with Rollup).

You sound like there is no real solution(?) At least the work-around is good enough for me for now. Alas, in the real-world version of the repos, I couldn’t let `lib` introduce context and use it via a hook.

**Comment by satya164** [comment] 2021-07-17 18:29
@rauschma in such scenarios, what I normally do is to use babel-plugin-module-resolver (or whatever module resolving mechanism available) to make sure that the package resolves to a single one.

**Comment by marvinhagemeister** [comment] 2021-07-17 18:35
> You sound like there is no real solution(?)

My comment was aimed at just relying on npm. The file syntax for dependencies only works for simple cases as it doesn't really understand the relationship between those two folders. It breaks for anything else.

Tools like `yarn workspaces` or `lerna` solve exactly this problem, which happens to be the same one as for monorepos where folders containe dependencies that depend on each other. Afaik npm is in the process of adding decent workspace support natively, but that may take a while.

**Comment by rauschma** [comment] 2021-07-17 18:47
Ah, good point. With a proper install, this should go away.

I’ll take a look at workspaces, thanks! I’ve also heard good things about pnpm.

**Comment by marvinhagemeister** [comment] 2021-07-17 20:46
Good point, `pnpm` workspaces work too 👍

**Comment by JoviDeCroock** [comment] 2021-12-03 18:04
Closing this issue as it seems resolved, TLDR: when we publish libraries we need to mark libraries that lean on being a singleton like Preact as an external

**Closed by JoviDeCroock** 2021-12-03 18:04 UTC
