### ISSUE TITLE
Hydrate results in two HTML DOMs

### ISSUE THREAD

**Issue by kanishk-anand-oyo** [preactjs/preact#2418] opened 2020-03-16 13:12 UTC
I am migrating a project from Preact 8 to Preact X, and have been successful in the migration, and after reading the documentation, I want to leverage the `hydrate` property, to make the preact-app more performant. But as soon as I use hydrate, inplace of render, it results in displaying the App twice, one from SSR, and one after CSR. 

On SSR I am using 

```
renderStylesToString(
   renderToString(
       <IntlProvider locale={appLocale.locale} messages={messages}>
            <CookiesProvider cookies={new Cookies(req.headers.cookie)}>
               <Provider store={store} key="provider">
                  <RouterContext {...renderProps} />
                 </Provider>
              </CookiesProvider>
         </IntlProvider>
       )
 );
```

and on CSR, the App is initialised using :

```
hydrate(
    <IntlProvider locale={locale} messages={appMessages}>
      <CookiesProvider>
        <Provider store={store}>
          <Router />
        </Provider>
      </CookiesProvider>
    </IntlProvider>,
    document.getElementById('root')
  );
```
I am using `renderStylesToString` due to usage of Emotion. Even after removing `renderStylesToString` , the HTML DOM appears twice. 

### Expected Behavior

It should render one App, while registering event handlers, and re-rendering only those components whose attributes/DOM differs.

### Actual Behavior
The HTML DOM appears once, while attaching event handlers.

**Comment by JoviDeCroock** [comment] 2020-03-16 13:17
Hey,

Could you provide a reproduction for this since it sounds like the actual dom being transmitted differs a lot from the one hydrated (only explanation I can come to at this point).

That being said, 

> and re-rendering only those components whose attributes/DOM differs.

Props aren’t diffed during hydration, this is expected

**Comment by kanishk-anand-oyo** [comment] 2020-03-16 13:26
Attaching screenshots for the reference, will provide a live URL in a while. 

SSR output : 
<img width="384" alt="Screen Shot 2020-03-16 at 6 37 28 PM" src="https://user-images.githubusercontent.com/35364381/76762392-3a1ee200-67b7-11ea-9de9-7197133ee1a5.png">

CSR output: 

<img width="379" alt="Screen Shot 2020-03-16 at 6 37 40 PM" src="https://user-images.githubusercontent.com/35364381/76762448-502ca280-67b7-11ea-84c2-be174c3b21d0.png">

Combined: 

![screencapture-kani-oyorooms-2020-03-16-18_52_07](https://user-images.githubusercontent.com/35364381/76762622-997cf200-67b7-11ea-8383-1a8d45f69102.png)

**Comment by JoviDeCroock** [comment] 2020-03-16 13:29
It would be easier for us if you could provide a [reproduction](http://codesandbox.io/), I don't mean to make this hard on you but it's very hard to derive what is being done from screenshots or hypothetical code examples where we don't know what the implementation of those components used are (in this case Providers).

**Comment by kanishk-anand-oyo** [comment] 2020-03-16 13:32
Sure, let me see how can I reproduce the same on sandbox.

**Comment by JoviDeCroock** [comment] 2020-03-16 13:32
Here's a start: https://codesandbox.io/s/keen-breeze-39fdh

**Comment by kanishk-anand-oyo** [comment] 2020-03-18 17:51
I created sample project with data flow similar to the main project, and for the sample project the hydrate function works fine. I guess I need to inspect what is causing the DOM to change drastically on client side. Thanks for the support!

**Comment by developit** [comment] 2020-07-14 16:17
Might be okay to close this issue since it's likely something to do with the specific SSR/CSR handling?

**Closed** 2020-07-14 16:18 UTC
Labels: needs-more-info

**Comment by kanishk-anand-oyo** [comment] 2020-07-14 16:20
Done. Seems like issue with application itself.
