### ISSUE TITLE
InvalidCharacterError whilst rendering Markdown-to-JSX

### ISSUE THREAD

**Issue by AJamesPhillips** [preactjs/preact#4083] opened 2023-07-27 07:57 UTC
- [x] Check if updating to the latest Preact version resolves the issue: 10.16.0

**Describe the bug**
[Markdown-to-JSX](https://github.com/probablyup/markdown-to-jsx) can produce some output that causes Preact to throw an exception.

**To Reproduce**

https://codesandbox.io/s/upbeat-agnesi-mdh9js?file=/components/app.js

1. Go to link above and see "InvalidCharacterError: String contains an invalid character"
2. Edit the code to remove the space in the "<s ->" to stop triggering the error.

Error can also show up as "DOMException: String contains an invalid character"

**Expected behavior**
Either not error or a way to catch and gracefully handle that error.

I've also posted this as a [potential bug with Markdown-to-JSX](https://github.com/probablyup/markdown-to-jsx/issues/507) incase it's easier to handle there.

**Comment by marvinhagemeister** [comment] 2023-07-27 10:26
It looks like the markdown parser is materialising `<s ->` into a HTMLElement tag `s` with the attribute `- == true`. Preact only sees the final vnode and when it tries to render that the browser throws the error.

To me that is not a bug in Preact. The browser is supposed to throw when trying to do invalid things. Rather this seems like a bug in the markdown parser.

**Comment by AJamesPhillips** [comment] 2023-07-27 10:38
Great thanks for the rapid exploration and explanation @marvinhagemeister, I couldn't figure out how to debug this further.  Much appreciated.  I thought I'd file the bug here as well as Markdown-to-jsx as React seems to handle this gracefully.  But happy to close this if you want.

**Comment by marvinhagemeister** [comment] 2023-07-27 10:54
When it comes to Preact one can debug the vnodes that are materialized via our `options` API. The `options.vnode` hook is called whenever a vnode is constructed for example:

```jsx
import { options } from "preact";

let oldVnode = options.vnode;
options.vnode = vnode => {
  console.log(vnode);
  if (oldVnode) oldVnode(vnode)
}
```

Ultimately that `vnode` object is then passed to the renderer unless some conditional branching in a component by the user renders something else.

I'm less sure off the top of my head on how to debug that in React. I'm a bit surprised that they don't throw there, but maybe they have an allowlist of valid html attributes and ignore everything else or something.

**Comment by JoviDeCroock** [comment] 2023-10-09 06:56
Going to close this as solved, feel free to keep discussing or re-open if something else pops up

**Closed by JoviDeCroock** 2023-10-09 06:56 UTC
