### ISSUE TITLE
`createElement` generates circular data structure in 10.0.0-rc.2

### ISSUE THREAD

**Issue by robertknight** [preactjs/preact#1916] opened 2019-09-09 20:59 UTC
The `h`/`createElement` function in Preact 10.0.0-rc.2 can generate a circular data structure, causing an infinite loop when the result is later passed to `render`.

**Steps to reproduce**

```js
const { h, render } = require('preact');

const el = h('div', null, h('span', null), h('br', null));

console.log('VDOM node is', el);
```

**Expected:** Non-circular data structure
**Actual:** Circular data structure. This causes an infinite loop in `toChildArray` when rendering.

Slack discussion: https://preact.slack.com/archives/G9T60GUQ0/p1568062137383300

**Comment by jviide** [comment] 2019-09-09 21:05
The problem is here: https://github.com/preactjs/preact/blob/9fb01cbb6a2e654bd0288fcec24ca70ddf94fa96/src/create-element.js#L12-L20

This bug is triggered when `h` gets more than three arguments (`arguments.length > 3`).

Because children is an argument then the statement `children =  []` is functionally equivalent to `arguments[2] = []`. Due to this the first iteration of the for-loop (i.e. `children.push(arguments[2])`) is functionally equivalent to `children.push(children)`. This in turn causes the cyclical structure.

**Comment by developit** [comment] 2019-09-10 03:29
@JoviDeCroock I wonder if it'd be better to revert the optimization we merged that caused this?

**Comment by antidotech** [comment] 2019-09-10 08:02
Temporal workarounds for people facing this issue:

Because it's about how `arguments` is handled by some modes, using esmodules should work. E.g. if you're using webpack, 
```ts
alias: { preact: 'preact/dist/preact.module.js' }
```
(make sure that file is not excluded in bundler/compiler)

cf: https://github.com/preactjs/preact/pull/1917#issuecomment-529694815

**Closed** 2019-09-10 16:25 UTC
