### ISSUE TITLE
React bootstrap PanelGroup accordion header disappear on click. 

### ISSUE THREAD

**Issue by uuuchit** [preactjs/preact#790] opened 2017-08-03 07:25 UTC
Using preact and preact-compat to a react app where react bootstrap was working fine. When switched to preact, panelgroup accordin started showing bug.  When we click on panel header/heading it disappears and further toggle is not possible  though panel body works fine. 
there were other error regarding refs in preact@8.2.* .. so i switched back to preact@8.1.0 but above error is still there. 
```javascript
import React, { Component } from 'react';
  import { Modal, Button, Accordion, PanelGroup, Panel } from 'react-bootstrap'

class About extends Component {
  getHeaderNode(){
    return (<div>
			<div className="col-md-3 col-sm-4 col-xs-4 pd-0">
				{`Room ${5}`}
			</div>
		</div>
             )
   }
  constructor(props){
    super(props)
    this.state ={
      arr: [1,2,3,4,5]
    }
  }
  
  render() {
    return (
      <div className="App">
          <h2>Error- when we click on panel header it disappears and further toggle is not possible</h2>
          {this.state.arr.map((item, i)=>{
            return (
              <PanelGroup defaultActiveKey="1" accordion>
                    <Panel key={i +1} header={this.getHeaderNode()} eventKey={(i+1).toString()}>
                      <p>Panel content will render here {item}</p>
                    </Panel> 
                  </PanelGroup>
            )
          })}
        </div>
    );
  }
}

export default About;
```
I have reproduced error in a git repo. 
https://github.com/uuuchit/panel

**Comment by developit** [comment] 2017-08-20 19:39
Hi there - this looks like a simple misuse of keys.  Remove all the keys and it will work fine.

**Comment by uuuchit** [comment] 2017-08-28 05:25
It is still not working.

**Comment by bboydflo** [comment] 2017-09-04 21:51
I had a similar issue and I fixed it by applying the jquery plugin in the upper most component in the `componentDidMount()`

**Comment by marvinhagemeister** [comment] 2020-01-08 16:40
Closing, a lot of bugs related to `keys` have been fixed in the current release line. Please ping us if you can still reproduce the described issue :+1:

**Closed by marvinhagemeister** 2020-01-08 16:40 UTC
Labels: feedback needed, question
