### ISSUE TITLE
refs is missing in declaration file

### ISSUE THREAD

**Issue by ccpu** [preactjs/preact#1206] opened 2018-09-08 18:50 UTC
I have noticed that having both preact and react types (@types/react) will confuse the typescript compiler and throw the following error:

'Property 'refs' is missing in type 'component'.'

apparently, the property 'refs' is missing from the 'preact.d.ts' declaration file.

adding the following code after line 101 in 'preact.d.ts' will solve the problem:

`   refs: {
      [key: string]: Component<any> | Element;
    };`

tried to submit a PR, but couldn't find the file mentioned.

Thanks

**Comment by developit** [comment] 2018-09-12 13:34
What is the reason for using both type definitions at the same time?

**Comment by kirilloid** [comment] 2018-10-04 11:48
I stumbled into the same problem using `preact` and `react-redux`. `connect` from `react-redux` uses `react`s type definitions and expects my component to have `refs`.

**Comment by koukimetal** [comment] 2018-10-16 12:47
I ran into exactly same problem. I'm not using \@types/react. I could compile but VS code says it's error.
@Cyrus-d 's solution helped me.

**Comment by weijarz** [comment] 2018-10-25 04:57
I ran into same problem. I'm using @types/flux, it installs @types/react to my node_modules and conflicts to preact.

**Comment by dumistoklus** [comment] 2018-11-28 21:04
I ran into same problem. I'm using @types/react-beautiful-dnd and @types/react-redux, it installs @types/react.

I think @developit should reopen this issue

**Comment by SolarLiner** [comment] 2019-01-09 19:35
For reference, installing storybook types will also install React types and confuse the compiler. If you're using Babel 7 you should switch to the TypeScript Babel plugin which simply doesn't check for types on build, or do without Storybook types.

**Comment by resynth1943** [comment] 2021-01-14 23:16
@developit would you accept a fix for this? It'd be nice to hear... _something_ from you, since this is affecting so many TypeScript users.

Here's what you get when you 'intermingle' Preact-typed and React-typed components.

![image](https://user-images.githubusercontent.com/49915996/104660418-613b8e00-56be-11eb-9608-66220c28ef5d.png)

**Comment by darklight9811** [comment] 2021-03-08 22:49
Any updates on this?

**Comment by Riku32** [comment] 2021-03-12 16:32
Yeah having the same issue

**Comment by andrewiggins** [comment] 2021-03-13 17:22
What version of Preact are you using? On master I'm seeing all references to the `ref` property marked as optional which I think would fix this issue.

**Comment by gpoitch** [comment] 2021-04-19 19:19
Hit this too. @andrewiggins it's complaining about `refs` (plural) which doesn't exist in preact's type file

**Comment by andrewiggins** [comment] 2021-04-19 19:49
Oh! `refs` with an `s`! 🤦‍♂️ My mistake - thanks for guiding me through that lol. 

I see. This is referring to the legacy string refs feature that Preact 10 doesn't have built in support for. Need to dig more into this and see what we can do.

**Comment by darklight9811** [comment] 2021-04-19 19:52
@andrewiggins, shouldnt this issue be reopened then?

**Comment by andrewiggins** [comment] 2021-04-19 22:23
Can someone help me with a minimal repo? Or perhaps modify my attempt to reproduce the error? I tried to get one here with react-redux but TypeScript didn't throw any errors: https://gist.github.com/andrewiggins/f16d86f60a98a4f58b5a0facb64b3f74 I'm sure I'm missing something simple....

Do be sure to share your source, package.json, and tsconfig file.

**Comment by mellis481** [comment] 2021-04-30 13:18
@andrewiggins New to using gists, but I've reproduced this issue which I was seeing with the dropdownRender property of antd's Select component.  https://gist.github.com/mellis481/517fb15b186b1d5d3aa494ce0f453517

You should see the issue on line 38.

**Comment by jaxreiff** [comment] 2021-06-04 16:36
Also experiencing this issue- in my case there is a `Property 'refs' is missing` error when I try to use Enzyme to `shallow` or `mount` render any component, which I would expect would be a fairly common use case.

**Comment by pierre-H** [comment] 2021-08-11 11:31
Same problem. Any news ?

**Comment by brykov** [comment] 2021-08-16 02:25
Started having this problem after adding https://github.com/uber/baseweb ans https://github.com/styletron/styletron to my project. Any news?

**Comment by snowinmars** [comment] 2022-02-01 20:49
> Can someone help me with a minimal repo? Or perhaps modify my attempt to reproduce the error? I tried to get one here with react-redux but TypeScript didn't throw any errors: https://gist.github.com/andrewiggins/f16d86f60a98a4f58b5a0facb64b3f74 I'm sure I'm missing something simple....
> 
> Do be sure to share your source, package.json, and tsconfig file.

Well, I don't have a minimal repo, but I have the issue [in my repository](https://github.com/snowinmars/aristotle.paraphrase/blob/preact-issue/src/fe/src/components/App/App.tsx#L28).

Ping `yarn start` to see the following errors.

```
ERROR in /home/homk/prg/snowinmars/aristotle.paraphrase/src/fe/src/components/App/App.tsx(28,8):
TS2786: 'Suspense' cannot be used as a JSX component.
  Its instance type 'Suspense' is not a valid JSX element.
    Property 'refs' is missing in type 'Suspense' but required in type 'ElementClass'.
ERROR in /home/homk/prg/snowinmars/aristotle.paraphrase/src/fe/src/components/App/App.tsx(29,10):
TS2786: 'Router' cannot be used as a JSX component.
  Its instance type 'Router' is not a valid JSX element.
    Property 'refs' is missing in type 'Router' but required in type 'ElementClass'.
Version: typescript 4.5.5

```

**Comment by TicTak21** [comment] 2022-05-05 14:24
+ 1

**Comment by bdombro** [comment] 2022-06-18 06:41
I was having this issue with Fragment, and adding this to preact.d.ts workfed for me:

```
export type Fragment = preact.JSX.Element
```

**Comment by DerGoogler** [comment] 2022-07-08 18:26
> A potential workaround for this:
> 
> preact.d.ts
> 
> ```ts
> namespace preact {
>   interface Component {
>     // This is a workaround for https://github.com/preactjs/preact/issues/1206
>     refs: Record<string, any>;
>   }
> }
> 
> declare module "preact" {
>   export = preact;
> }
> ```

No, use this:

`global.d.ts`

```ts
export {};

declare global {
  namespace preact {
    interface Component {
      // This is a workaround for https://github.com/preactjs/preact/issues/1206
      refs: Record<string, any>;
    }
  }
}
```

**Comment by mike-lischke** [comment] 2022-12-09 10:12
A good minimal examples for this problem is the typescript example in the [enzyme-adapter-preact-pure module](https://github.com/preactjs/enzyme-adapter-preact-pure/tree/master/examples/typescript). It builds and runs fine in a terminal, but fails to do so in VS Code.

Side note: the file structure in preact has changed meanwhile and the simplest workaround I found was to add a ref definition in the `Component` interface in node_modules/preact/src/index.d.ts

```typescript
    componentDidCatch?(error: any, errorInfo: ErrorInfo): void;
    refs: { [key: string]: Component<any> | Element; };
```

@developit Another reason for mixing the types is when using a library (like `enzyme`) which was originally written for React.

**Comment by JoviDeCroock** [comment] 2024-11-01 12:18
We could essentially add this property but given that this is for a deprecated API I am leaning on the "won't fix" route. You can always `declare module` and override this with a component type that does have refs.

**Closed by JoviDeCroock** 2024-11-01 12:18 UTC
