### ISSUE TITLE
preact/compat tree shakability

### ISSUE THREAD

**Issue by samouri** [preactjs/preact#3295] opened 2021-10-27 20:43 UTC
**summary**

I noticed that when importing from `preact/compat`, much more is pulled in than expected. For example, when bundling code like this:

```js
import { forwardRef } from 'preact/compat';
```

It creates ~2x greater binary size than directly copy/pasting the necessary function.

I've created a minimal reproduction here: https://github.com/samouri/preact-shakability

**Comment by senpro-ingwersenk** [comment] 2024-08-21 11:16
Originally posted in 2021, still open and apparently still a problem?

Is someone working on this?

**Comment by rschristian** [comment] 2024-08-22 08:24
As the "after X" tag indicates, it's something we can't safely change in Preact X.

It's something we'd like to address in the future, at least in part (some of compat will always be unshakable in all likelihood), but there's nothing anyone can change about this now.

**Comment by JoviDeCroock** [comment] 2024-11-30 07:09
Going to close this as a duplicate of https://github.com/preactjs/preact/issues/1529

**Closed by JoviDeCroock** 2024-11-30 07:09 UTC
Labels: after X, feature request
