### ISSUE TITLE
New DevTools doesn't work with `8.5.2`

### ISSUE THREAD

**Issue by flexdinesh** [preactjs/preact#1907] opened 2019-09-02 00:01 UTC
Just upgraded the project to `8.5.2` and the new Dev Tools still doesn't work.

Dropping be to see if this is something missing on my side. I am receiving this error in the console.

```js
Uncaught (in promise) TypeError: Cannot read property '_topLevelWrapper' of undefined
```

**Comment by marvinhagemeister** [comment] 2019-09-02 04:11
Duplicate of #1882.

**Closed by marvinhagemeister** 2019-09-02 04:11 UTC
