### ISSUE TITLE
componentDidCatch and act not working as expected

### ISSUE THREAD

**Issue by calebeby** [preactjs/preact#1875] opened 2019-08-17 07:20 UTC
:wave: I think I found a bug :slightly_smiling_face:

https://github.com/calebeby/preact-act-bug

I have a _feeling_ it is more of a bug with `componentDidCatch` than it is with `act`, but maybe not.

```js
const ThrowingComponent = () => {
  throw new Error('its a broken component')
}

class ErrorBoundary extends Component {
  componentDidCatch(error) {}
  render() {
    return this.props.children
  }
}

test('act', () => {
  jest.spyOn(console, 'error').mockImplementation(() => {})
  act(() => {
    const target = document.createElement('div')
    render(
      <ErrorBoundary>
        <ThrowingComponent />
      </ErrorBoundary>,
      target,
    )
  })
})
```

In React, this passes, in Preact, it doesn't. Somehow the error is escaping past the `componentDidCatch` and up into the test, causing the test to fail. Any idea why?

It isn't _because_ of `act`. The 2nd test in each file in the repro repo doesn't use act, and you can still see the issue (the uncaught promise error in the console). I think `act` is just making the issue more visible by synchronously causing the error to show itself.

**Comment by calebeby** [comment] 2019-08-17 07:20
The repro repo has the test for both React and Preact: https://github.com/calebeby/preact-act-bug

cc @robertknight this is the issue I mentioned when we were talking on Slack earlier

**Comment by calebeby** [comment] 2019-08-17 07:27
Is this somehow being called when it shouldn't be? https://github.com/preactjs/preact/blob/master/src/diff/index.js#L356

**Comment by JoviDeCroock** [comment] 2019-08-17 09:42
This test passes ```
	it.only('act', () => {
		let spy = sinon.spy();
		const ThrowingComponent = () => {
			spy();
		};

		class ErrorBoundary extends Component {
			componentDidCatch(error) {
				console.error('hi');
			}
			render() {
				return this.props.children;
			}
		}

		act(() => {
			render(
				<ErrorBoundary>
					<ThrowingComponent />
				</ErrorBoundary>,
				scratch,
			);
		});

		expect(spy).to.be.calledOnce;
	});
```

**Comment by calebeby** [comment] 2019-08-17 16:40
@JoviDeCroock your test passes because there isn't anything that throws 😕

`ThrowingComponent` renders `undefined`

**Comment by JoviDeCroock** [comment] 2019-08-18 09:10
Oh darn, I removed the throw for some reason. My bad will check again tonight

**Comment by JoviDeCroock** [comment] 2019-08-18 19:06
Still works though

```
	it.only('act', () => {
		let spy = sinon.spy();
		const ThrowingComponent = () => {
			throw new Error('Fatal');
		};

		class ErrorBoundary extends Component {
			componentDidCatch(error) {
				spy();
				this.setState({ error });
			}
			render() {
				return this.state.error ? 'error' : this.props.children;
			}
		}

		act(() => {
			render(
				<ErrorBoundary>
					<ThrowingComponent />
				</ErrorBoundary>,
				scratch,
			);
		});

		expect(spy).to.be.calledOnce;
		expect(scratch.innerHTML).to.equal('error');
	});
```

**Comment by developit** [comment] 2019-09-09 19:54
Is it possible the difference here is that @JoviDeCroock's version invokes setState() from within componentDidCatch? I can't say I've ever used componentDidCatch without a setState.

**Comment by JoviDeCroock** [comment] 2020-10-24 09:26
Closing issue since it seems to be working as intended.

**Closed by JoviDeCroock** 2020-10-24 09:26 UTC
