### ISSUE TITLE
Preact is not working for tailwindcss & react-icons

### ISSUE THREAD

**Issue by coffee419** [preactjs/preact#4411] opened 2024-06-17 10:07 UTC
Dear Support Team. How are you ? 

I hope you help me about my problem. now I am working with tailwindCSS with React-Icons in Preact Project.
but if I am going to use React-Icons, there are happening any mistake like attached Image.

![image](https://github.com/preactjs/preact/assets/109244102/2f87a58f-08af-48a6-93b8-816d38327441)

How can I use tailwindcss with react-icons ? 

I hope you help me please.

thanks

**Comment by JoviDeCroock** [comment] 2024-06-17 10:11
Preact core leverages `class` rather than `className`, when you are using `compat` `className` will work however, this looks to be erroring because there is some aliasing going on in your TypeScript types as normally the compat intrinsicAttributes should contain className as well. You might need to check how your declaration merging is going.

**Comment by JoviDeCroock** [comment] 2024-06-17 10:18
Hmm, we might need to fix this by adding `class` and `className` here https://github.com/preactjs/preact/blob/main/src/jsx.d.ts#L30-L32

**Comment by rschristian** [comment] 2024-06-17 10:33
Posted this on Slack too, but...

Doesn't look like it's a vallid issue. `react-icons` don't take a `className` prop, this is 100% working as intended from what I can see: https://github.com/react-icons/react-icons?tab=readme-ov-file#adjustment-css

**Comment by coffee419** [comment] 2024-06-17 10:35
> Posted this on Slack too, but...
> 
> Doesn't look like it's a vallid issue. `react-icons` don't seem to take a `className` prop: https://github.com/react-icons/react-icons?tab=readme-ov-file#adjustment-css

but I used react-icons with `className` in other react project.

**Comment by JoviDeCroock** [comment] 2024-06-17 10:38
Have you tried checking whether that previous project had non-up-to-date versions of things? That being said our minimum requirement is a reproduction, you are also duplicating issues as you are asking for help on both Slack as well as GitHub. We can't help you on both mediums as you are just duplicating effort, I'll close this one as it doesn't suffice with our minimum requirements and we can continue this conversation on slack.

**Closed by JoviDeCroock** 2024-06-17 10:38 UTC

**Comment by rschristian** [comment] 2024-06-17 10:41
I would also guess you're using different versions, as, per those docs I linked, `react-icons` changed this in some version.

For the current setup anyhow, [`MdDeleteForever` is of `IconType`](https://www.runpkg.com/?react-icons@5.2.1/md/index.d.ts#109) and [`IconType` doesn't take a `className` prop](https://www.runpkg.com/?react-icons@5.2.1/lib/iconBase.d.ts#16)
