### ISSUE TITLE
contenteditable broken with Preact 10

### ISSUE THREAD

**Issue by SnoopyKIWI** [preactjs/preact#2691] opened 2020-08-09 17:23 UTC
### Reproduction

```
<!DOCTYPE html>
<meta charset="UTF-8">
<style>
	span {
		border: 1px solid #000;
	}
	span:empty::after {
		content: 'placeholder';
		font-size: smaller;
		left: 0;
		opacity: 0.5;
		top: 0;
	}

</style>
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/preact/8.5.3/preact.dev.js" integrity="sha512-X4tdt+//Fj3d6uBdK8YH5qHT7g0mDWf4ZOJS5UQj7OJu+QAy53ySvOoAe1iky/oZ8JaUaHLAHI2swH2SGnGzWg==" crossorigin="anonymous"></script> -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/preact/10.4.7/preact.umd.min.js" integrity="sha512-dHedEHbrmayd9MzZJGcsUVzD2to6afhlJiXkDYzUBl3qrNOFE4nK1BsPnzSve6K3vTlMcmQLToPJGxs3gbsyew==" crossorigin="anonymous"></script>
<script>
	const { Component, h, render } = self.preact;

	class Editable extends Component {
		constructor(props) {
			super(props);
			const { value } = props;
			this.setState({ value });

			this.onInput = (event) => {
				const value = event.target.innerText;
				this.setState({ value });
			};
		}

		render(props, { value }) {
			return h('div', {},
				h('span', {
					contenteditable: true,
					onInput: this.onInput,
				}, value),
			);
		}
	}

	document.addEventListener('DOMContentLoaded', () => {
		render(h(Editable, {}), document.body);
	});
</script>
```

### Steps to reproduce
1. Apply the above HTML code (using Preact 10, where Preact 8 is commented).
2. Click inside placeholder box and start typing.

### Expected Behavior
The letters typed should be echoed inside the span as you type them. This used to work correctly in Preact 8 (try commenting Preact 10 and uncommenting Preact 8).

### Actual Behavior
Typed letters are replicated n times, where n is the number of characters typed.
The problem happens when the initial state (derived from props) has an empty `value`.

**Comment by marvinhagemeister** [comment] 2020-08-11 08:14
Some preliminary findings:

- Binding to the `change` event of `input` works
- Skipping diffing of `children` if `contenteditable=true` works too

**Comment by developit** [comment] 2020-08-11 13:53
Out of curiosity, what's the use-case for this? 

The behavior of this setup (contentEditable + children) has always been undefined and broken in Preact. In your example when using Preact 8, try using `cmd+B`/`ctrl+B` to bold some text - it gets appended to the end of the input again. Inserting newlines by pressing enter increases the height of the editable region, but collapses the newlines because you're using `innerText` (preserves newlines) but assigning via `Text.data` (doesn't preserve them).

The only officially supported way to assign the value of a `contentEditable` region is `dangerouslySetInnerHTML`:

```diff
class Editable extends Component {
  constructor(props) {
    super(props);
    const { value } = props;
    this.setState({ value });

    this.onInput = (event) => {
-     const value = event.target.innerText;
+     const value = event.target.innerHTML;
      this.setState({ value });
    };
  }

  render(props, { value }) {
    return h('div', {},
      h('span', {
        contentEditable: true,
        onInput: this.onInput,
+       dangerouslySetInnerHTML: {
+         __html: value
+       }
+     })
-     }, value)
    );
  }
}
```

However, the issue here actually isn't related to child diffing at all: it's that you're using `event.target`. The `event.target` property of an `onInput` event points to the element that generated that event, which in this case is a Text node or element within your contentEditable span, not the span itself. Preact 8 aggressively merged text children, so it happened that an all-text value for the contentEditable avoided triggering this behavior. That's why inserting bold didn't work, and it's why inserting a newline via `enter` caused that newline to be appended permanently to the span.

This can be fixed so that it works the same in both Preact 8 and Preact X by using a ref instead of `event.target`:

```diff
	const { Component, h, render } = self.preact;

	class Editable extends Component {
		constructor(props) {
			super(props);
			const { value } = props;
			this.setState({ value });

+			this.ref = element => {
+				this.element = element;
+			};

			this.onInput = (event) => {
-				const value = event.target.innerText;
+				const value = this.element.innerText;
				this.setState({ value });
			};
		}

		render(props, { value }) {
			return h('div', {},
				h('span', {
					contenteditable: true,
					onInput: this.onInput,
				}, value),
			);
		}
	}

	document.addEventListener('DOMContentLoaded', () => {
		render(h(Editable, {}), document.body);
	});
```

**Comment by marvinhagemeister** [comment] 2020-08-11 14:29
@developit That's an excellent find! Never would've thought about that. Found another fix for that, that's shorter. To get the element the listener was called on, we can leverage `event.currentTarget` and thereby sidestep the whole ref dance.

```patch
  this.onInput = (event) => {
-   const value = event.target.innerText;
+   const value = event.currentTarget.innerText;
    this.setState({ value });
  };
```

**Comment by SnoopyKIWI** [comment] 2020-08-13 22:44
I tried this example with references, using the exact code you suggested. The problem persists (in Preact X). Adding a log statement to the `onInput` and typing the word "something" in the field, the log shows:
```
s
sos
somsos
somesomsos
sometsomesomsos
somethsometsomesomsos
somethisomethsometsomesomsos
somethinsomethisomethsometsomesomsos
somethingsomethinsomethisomethsometsomesomsos
```
The main issue isn't the use of `event.target` because the same behavior is observed when using the reference; I'm not sure why the ref didn't work. Both compute the correct value (in the sense that it's the exact text inside the span, despite whichever element caused the event). The problem seems more related to the feedback of rendering the value from state, which appears to be prepending the new text to previous text inside the span (or perhaps appending the previous text to the existing, I can't tell) instead of fully overwriting that text.

I've tried the `dangerouslySetInnerHTML` technique (couldn't find this in the Preact docs), but that has another unexpected behavior: the value appears in reverse order:
```
s
os
mos
emos
temos
htemos
ihtemos
nihtemos
gnihtemos
```
At least this is consistent between Preact 8 & X. This makes sense to me: the render is overwriting the `innerHTML` directly but the browser doesn't know where to position the cursor so it resets the index to zero.

The use case is toggling between read-only and editable not-very-rich text: a single-line variant like `<input>` but with varied sizing and sane styling, and a multi-line variant like `<textarea>` but with automatic sizing, word-wrap, and sane styling. (It's maddening how browsers style input/textarea fields and that they doesn't support automatic sizing with a simple attribute.) I was trying to avoid this type of component: click-to-edit, change a span/div into an input while editing, and convert back to the span/div on blur, all while keeping everything visually consistent between edit and read-only modes. Using `innerHTML` instead of `innerText` has the same problem, except without the desired non-rich behavior.

I'm aware of the other issues you described (bold, inserting newlines, etc.) and have some ugly workarounds. The example I provided was the simplest I could make to illustrate the problem. Strangely, this problem only seems to happen when the initial value is blank! If the component is constructed with a non-blank value, it works as expected in all versions of Preact.

**Comment by sventschui** [comment] 2020-08-14 07:04
So here is a repro case: https://codesandbox.io/s/ecstatic-grass-3imqe

I have added 3 examples, 2 of them are broken-ish.

### Using `value` as a child (vnode) (broken by design)

This works great up until the point where one clears the input using `Cmd+A -> Cmd+X` (or `Cmd+A -> Backspace`) and starts typing again. From then on the issue @SnoopyKIWI mentioned kicks in: Duplicated content in the DOM. This is what @developit mentioned above.

### Using `dangerouslySetInnerHTML`

This doesn't work well from the get go: It suffers from a jumping cursor.

### Using an uncontrolled contenteditable

This is the only thing that currently works. This offers the best performance but makes things like resetting the content a bit different (i.e. calling `ref.current.innerText = 'Whatever'` instead of `setValue('Whatever')`. 


### Conclusion

Although I'd personally always recommend uncontrolled components for performance reasons I do not want to start a discussion about that here. We should support the dangerouslySetInnerHTML approach mentioned above. @developit agree?

**Closed** 2020-08-30 15:29 UTC
Labels: known issue, workaround
