### ISSUE TITLE
Typescript FunctionComponent

### ISSUE THREAD

**Issue by fabiodcorreia** [preactjs/preact#1566] opened 2019-04-24 10:11 UTC
Hi, maybe I'm missing something but here is the situation. I have a functional component with this signature:
``` javascript 
const Input : FunctionComponent<Props> = (props: Props)
``` 

Then using Storybook for Preact I have the following story
``` javascript 
storiesOf('Input', module)
    .add('Sample', () => <Input type="text" />)
``` 

And in this situation I get a typescript validation error with the following message at the story level.
`JSX element type 'VNode<{}>' is not a constructor function for JSX elements.`
`Type 'VNode<{}>' is missing the following properties from type 'Element': nodeName, attributes, children`

So I **add** method is expecting a **RenderFunction** which is an alias to one or more **Preact.AnyComponent** or  **JSX.Element**.

Then I checked the **FunctionComponent** and it return a function that returns **VNode** or **null**.

So I checked and **JSX.Element** extends **VNode<any>** so this should be correct. But doesn't work.

If on **index.d.ts** I changed the interface

``` javascript
interface FunctionComponent<P = {}> {
    (props: RenderableProps<P>, context?: any): VNode | null;
    displayName?: string;
    defaultProps?: Partial<P>;
}
```
To
``` javascript
interface FunctionComponent<P = {}> {
    (props: RenderableProps<P>, context?: any): preact.JSX.Element | null;
    displayName?: string;
    defaultProps?: Partial<P>;
}
```
Then the error gets solved but I'm not sure this is correct or if I'm doing something wrong. 
Btw I'm using the latest release of preact

**Comment by JoviDeCroock** [comment] 2019-04-29 16:43
I don't use TypeScript at this point but it would seem logical that a `preact.JSX.Element` is the return value of render rather than a vnode.

**Comment by marvinhagemeister** [comment] 2019-05-07 17:54
FYI: Here is the relevant type from `@types/react`: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/4ef82c966a21c7f54f7c360eec5df4787c6d971e/types/react/index.d.ts#L100-L104

**Comment by ForsakenHarmony** [comment] 2019-05-08 16:20
Have you configured `jsxFactory`?

**Comment by fabiodcorreia** [comment] 2019-05-12 09:53
> Have you configured `jsxFactory`?

Yes the 'h' is configured as jsxFactory on tsconfig

**Comment by ForsakenHarmony** [comment] 2019-05-19 16:49
Can you try it with `'preact.h'`?

**Comment by Autarc** [comment] 2019-05-26 22:26
Got the same issue with `10.0.0-beta.1`. Changing the TypeScript configuration value of `jsxFactory` to `preact.h` unfortunately doesn't help. Has someone another idea?

**Comment by ForsakenHarmony** [comment] 2019-05-26 22:38
Wait, which typings are you using for storybook?

**Comment by Autarc** [comment] 2019-05-26 22:56
The one which we're recommend for the package: [@types/storybook__preact]( https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/storybook__preact). Do you think it might be caused by [the Renderable](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/storybook__preact/index.d.ts#L12)?

**Comment by cortopy** [comment] 2019-07-31 20:41
@fabiodcorreia thank you for posting this issue! I was puzzled by this and you put me in the right path. I've just made a PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37275 that fixes it. Instead of changing preact types, the problem lies with the storybook types.

When JSX is configured with preact's `h`, a function returns an `Element` rather than the component itself. In the case of React this is straightforward, but in the case of preact we have to acknowledge it in any other types too

**Comment by cortopy** [comment] 2019-07-31 21:20
damn, unfortunately tests are not passing. Typical scenario....working in local but not in CI :cry:

**Comment by ForsakenHarmony** [comment] 2019-07-31 21:27
the storybook preact typings are probably not compatible with preact x

**Comment by cortopy** [comment] 2019-07-31 21:29
I'm using preact x, it seems fine with my change

**Comment by ddayguerrero** [comment] 2019-08-05 19:41
@cortopy having a similar issue with the `RenderFunction` callback when using latest Preact X and storybooks for Preact

```
Type 'Element' is not assignable to type 'FunctionalComponent<{}> | ComponentConstructor<{}, {}> | Element | Renderable[]'.
  Type 'Element' is missing the following properties from type 'Element': nodeName, attributes, childrents(2322)
```

`export type Renderable = Preact.AnyComponent | JSX.Element | preact.JSX.Element;` in the typings does the job for me

**Comment by cortopy** [comment] 2019-08-06 08:15
@ddayguerrero that's awesome!! I tried to do a similar PR exactly, but dtslint was failing all the time

**Comment by ForsakenHarmony** [comment] 2019-08-07 23:11
Is the issue resolved with that PR?

**Comment by ddayguerrero** [comment] 2019-08-08 01:29
In my case, the new typings for storybook work well with Preact X. I'd double check with @fabiodcorreia to see which "latest version" is being referred in the original post.

**Closed** 2019-12-25 20:53 UTC
Labels: types

**Comment by gianpaj** [comment] 2020-07-16 11:36
For others arriving here for a similar issue.

This fails:
```ts
const Avatar = (props: IProps): FunctionalComponent<IProps> => {

  return (
    <span>
     hello
    </span>
  );
};
export default Avatar;
```
Error in the return:
```
Type 'Element' is not assignable to type 'FunctionalComponent<IProps>'.
  Type 'Element' provides no match for the signature '(props: Readonly<IProps & Attributes & { children?: ComponentChildren; ref?: RefObject<any> | RefCallback<any> | undefined; }>, context?: any): VNode<...> | null'.
```
and error when using this component:
```
'Avatar' cannot be used as a JSX component.
  Its return type 'FunctionalComponent<IProps>' is not a valid JSX element.ts(2786)
```


This is correct:
```ts
const Avatar: FunctionalComponent<IProps> = (props: IProps) => {

  return (
    <span>
     hello
    </span>
  );
};
export default Avatar;
```

the component <ins>**should be**</ins> a FunctionalComponent. It doesn't return one
