### ISSUE TITLE
Get rid of made up propNames

### ISSUE THREAD

**Issue by titoBouzout** [preactjs/preact#4555] opened 2024-11-12 18:21 UTC
- [ ] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
I have been watching the updates to the JSX types and I think it would be a good idea to get rid of the "made up props".

Definition: 
made up props: are props that look like these exists, but these don't really exist. 

Examples: `<audio>.autoPlay`, there isn't an `autoPlay` property. Granted it could be more readable, but then if the user for whatever reason has to do `node.autoPlay` that won't work, because `autoPlay` doesn't exist. It is `autoplay`

I think it leads to unnecessary and avoidable confusion.

Some more examples of this problem include:

 `<audio>.autoPlay` autoplay
 `<audio>.playsInline` playsinline

 `<button>.autoFocus` autofocus
 `<button>.formEncType` formenctype

 `<iframe>.allowFullScreen` allowfullscreen
 `<iframe>.srcDoc` srcdoc

 `<input>.autoComplete` autocomplete
 `<input>.enterKeyHint` enterkeyhint

There are more on this table https://potahtml.github.io/namespace-jsx-project/index.html marked as 🛑

**Expected behavior**

To not provide typings for "made up propNames", instead maybe you could mark any of these as `deprecated` and suggest a proper attribute/propName.

I understand you provide compatibility with React, but the properties I am talking about aren't really that many, and pushing away from them sounds like a good idea..

**Comment by rschristian** [comment] 2024-11-12 19:16
While I think most of us mirror your sentiments around the strange renaming React has done and prefer the casing of the platform (even though it's incredibly inconsistent), I don't think we can be the drivers of change here, given our situation.

Compat is a huge part of our ecosystem, and because we have no intention of making these casings no longer work, marking them as deprecated feels like a poor choice that's likely to confuse users. Maybe we can add a comment to each with a gentle nudge to use the platform casing instead? Deprecating feels like a step too far right now, IMO.

If you can manage to convince React (which I find unlikely), maybe then we can mark them as deprecated in a year or two, but I think they'll need to switch before we touch our types here.

**Comment by rschristian** [comment] 2024-11-19 05:19
While I generally lean toward deprecating the non-standard _types_ in core, leaving them to compat, some do prefer those types and it'd reduce copy & pastability, so I think we should close this out. Nevertheless, this is something that'll certainly remain in the back of our minds, it does come up fairly often, and maybe we'll reconsider in the future at some point. I think we need to keep this as-is for now & accept that the non-standard types are, for better or for worse, "working as intended".

Thanks for raising the issue though, gave another round of thought & discussion at least.

**Closed by rschristian** 2024-11-19 05:19 UTC
Labels: compat, types
