### ISSUE TITLE
Replacing import { h } with React doesn't work in jest tests

### ISSUE THREAD

**Issue by ssuvorov** [preactjs/preact#2182] opened 2019-12-13 09:13 UTC
Steps to reproduce:
1. `$ preact create default preact` (preact-cli v2.2.1)
`cd ./preact`
2. `npm i -D @babel/plugin-transform-react-jsx`
3. Update **package.json**
```
"jest": {
    ...
    "moduleNameMapper": {
      "react": "preact/compat",
      "react-dom/test-utils": "preact/test-utils",
      "react-dom": "preact/compat"
    }
  }
```
4. in **header.test.js** replace `import { h } from 'preact'` with
`import React from 'react'`
5. in **.babelrc** add
```
plugins: [
        ['@babel/plugin-transform-react-jsx', {
          "pragma": "h",
          "pragmaFrag": "Fragment"
        }]
      ]
```

 **FAIL  tests/header.test.js**
  ● Test suite failed to run

    TypeError: Cannot read property 'prototype' of undefined

      3 | 
      4 | configure({
    > 5 | 	adapter: new Adapter()
        | 	                                                    ^
      6 | });
      7 | 

      at node_modules/preact/compat/dist/compat.js:1:469
      at Object.<anonymous> (node_modules/preact/compat/dist/compat.js:1:611)
      at Object.<anonymous> (tests/__mocks__/setupTests.js:5:55)

**Comment by marvinhagemeister** [comment] 2019-12-13 09:23
This is a misconfiguration of the babel plugins. By default `@babel/plugin-transform-react-jsx` will use `React.createElement` as the jsx constructor function. If you manually change that to `h`, but don't import the function anywhere, than this will break. If you want to use `import React from 'react'` instead, you need to change the pragma settings accordingly.

```js
plugins: [
  ['@babel/plugin-transform-react-jsx', {
    "pragma": "React.createElement",
    "pragmaFrag": "React.Fragment"
  }]
]
```

**Comment by SolarLiner** [comment] 2019-12-13 09:26
I'll add that by default `@babel/plugin-transform-react-jsx` will use `React.createElement` and `React.Fragment`, therefore in your `.babelrc` you may just write:

```json
plugins: ["@babel/plugin-transform-react-jsx"]
```

**Comment by SolarLiner** [comment] 2019-12-13 09:56
@marvinhagemeister I can actually reproduce the issue; I am not sure if this is from Preact, Preact CLI or Jest though.

**Comment by marvinhagemeister** [comment] 2019-12-13 10:46
Alright, reopening

**Comment by JoviDeCroock** [comment] 2019-12-16 10:12
I think the issue is the following:

For `Preact-cli` we use `babel-jest` and our own `createConfig` [here](https://github.com/preactjs/preact-cli/blob/master/packages/jest-preset-preact/src/babel-jest.js) when we go look at that config we see that `babelrc: false` which means we aren't allowing any custom overrides from your `babelrc`. By default we're using https://github.com/preactjs/preact-cli/blob/master/packages/cli/lib/lib/babel-config.js#L34 making it use the wrong default

**Comment by ssuvorov** [comment] 2019-12-16 14:08
@JoviDeCroock I also have a project without `preact-cli` and there on `npm test` the error is:
```
TypeError: Cannot read property 'prototype' of undefined
      at node_modules/preact/compat/src/PureComponent.js:11:31
      at Object.comparer (node_modules/preact/compat/src/memo.js:11:25)
```
It might be misconfiguration, but also can be related to the same issue.

**Comment by ka2n** [comment] 2020-01-08 17:23
Changing `moduleNameMapper` key to regexp form will fix this issue (At least in my case).

```
  moduleNameMapper: {
    "^react$": "preact/compat",
    "^react-dom$": "preact/compat",
    "^react-dom/test-utils$": "preact/test-utils",
  },
```

background:

I ran a jest test with the Chrome Remote Debugger and found that `require ('preact')` in `preact/compat` only returned a empty object(`{}`). Then `preact/compat` try to extend `require('preact/comat').Component`, but it's `undefined` in this situation.

**Comment by alxclark** [comment] 2020-01-15 22:44
@ka2n Had the same issue than mentionned by @ssuvorov and it worked for me as well! 🙏

**Comment by ssuvorov** [comment] 2020-01-16 16:49
guys, if you have your custom configuration file, could you check the next, please:

```diff
"moduleNameMapper": {
-      "config": "<rootDir>/src/configuration/config.development.js",
+      "^config": "<rootDir>/src/configuration/config.development.js",
     ...
}
```
After I changed that, it works for me

**Comment by rschristian** [comment] 2024-04-19 05:45
Closing as it's been a few years and might've been a misconfiguration elsewhere? If anyone still has problems, please open a new issue.

**Closed by rschristian** 2024-04-19 05:45 UTC
