### ISSUE TITLE
Suspended nodes producing TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by birtles** [preactjs/preact#3083] opened 2021-03-25 10:15 UTC
- [ ] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
(Sorry, this is going to be a really vague bug description. I don't have a minimal test case yet but I think I've debugged far enough to have some sense of the problem.)

Under some circumstances where `setState` is called early in the rendering pipeline (before the first complete render?) I encounter a stack like the following:

<details>

```
preact.module.js?da65:formatted:1 Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
    at g (preact.module.js?da65:formatted:1)
    at g (preact.module.js?da65:formatted:1)
    at g (preact.module.js?da65:formatted:1)
    at g (preact.module.js?da65:formatted:1)
    at g (preact.module.js?da65:formatted:1)
    at g (preact.module.js?da65:formatted:1)
    at g (preact.module.js?da65:formatted:1)
    at g (preact.module.js?da65:formatted:1)
    at g (preact.module.js?da65:formatted:1)
    at g (preact.module.js?da65:formatted:1)
g @ preact.module.js?da65:formatted:1
g @ preact.module.js?da65:formatted:1
g @ preact.module.js?da65:formatted:1
g @ preact.module.js?da65:formatted:1
g @ preact.module.js?da65:formatted:1
g @ preact.module.js?da65:formatted:1
g @ preact.module.js?da65:formatted:1
g @ preact.module.js?da65:formatted:1
g @ preact.module.js?da65:formatted:1
g @ preact.module.js?da65:formatted:1
g @ preact.module.js?da65:formatted:1
g @ preact.module.js?da65:formatted:1
m @ preact.module.js?da65:formatted:1
I @ preact.module.js?da65:formatted:1
m @ preact.module.js?da65:formatted:1
I @ preact.module.js?da65:formatted:1
eval @ preact.module.js?da65:formatted:1
b @ preact.module.js?da65:formatted:1
Promise.then (async)
k @ preact.module.js?da65:formatted:1
p.setState @ preact.module.js?da65:formatted:1
i.__c.i.__ @ hooks.module.js?30ec:formatted:1
updateSetting @ context.tsx?e56e:145
getPreferredLang @ preferred-lang.ts?e1cc:45
eval @ provider.tsx?9570:104
d @ hooks.module.js?30ec:formatted:1
I18nProvider @ provider.tsx?9570:100
M @ preact.module.js?da65:formatted:1
I @ preact.module.js?da65:formatted:1
m @ preact.module.js?da65:formatted:1
I @ preact.module.js?da65:formatted:1
m @ preact.module.js?da65:formatted:1
I @ preact.module.js?da65:formatted:1
m @ preact.module.js?da65:formatted:1
I @ preact.module.js?da65:formatted:1
m @ preact.module.js?da65:formatted:1
I @ preact.module.js?da65:formatted:1
m @ preact.module.js?da65:formatted:1
I @ preact.module.js?da65:formatted:1
N @ preact.module.js?da65:formatted:1
eval @ index.tsx?d986:17
./src/index.tsx @ 10ten.cc58e190847086ba5a6d.js:530
__webpack_require__ @ 10ten.cc58e190847086ba5a6d.js:1113
(anonymous) @ 10ten.cc58e190847086ba5a6d.js:1538
(anonymous) @ 10ten.cc58e190847086ba5a6d.js:1542
```

</details>

Digging through the source I can see that `g` corresponds to [`reorderChildren`](https://github.com/preactjs/preact/blob/4e29ec70332c8c1c7cfb002d4069f2c9db2831f2/src/diff/children.js#L246) and the specific error is that `childVNode._children` is undefined in:

https://github.com/preactjs/preact/blob/4e29ec70332c8c1c7cfb002d4069f2c9db2831f2/src/diff/children.js#L246-L248

Going up the stack a bit I can see this is called by `diffChildren` which includes the following code:

https://github.com/preactjs/preact/blob/4e29ec70332c8c1c7cfb002d4069f2c9db2831f2/src/diff/children.js#L162-L171

The check for `childVNode._children != null`, being non-strict inequality, should correctly ensure that `reorderChildren` is not called even if `childVNode._children` is `undefined`.

Howevever, `reorderChildren` calls itself recursively and we don't perform that test before calling ourselves. i.e. we don't check that `vdom._children != null` in:

https://github.com/preactjs/preact/blob/4e29ec70332c8c1c7cfb002d4069f2c9db2831f2/src/diff/children.js#L256-L258

Unfortunately I can only reproduce this consistently through some fairly complicated steps in a fairly complex app, however, I previously encountered it when using `useLayoutEffect()` to call `setState` as part of the initial render (for an app that includes Suspend lower down the tree) so it might be possible to reproduce using such an approach.

Update (2021-03-25): Fixed reference to `oldDom._children != null` to `vdom._children != null`.

**Comment by birtles** [comment] 2021-03-25 11:46
For what it's worth I managed to stop the debugger at the point where the error was about to occur. As you can see, the "Lazy" component has an undefined `__k` (`_children`) member but it has a `type` that is a function so it will be passed along to `reorderChildren`.

<img width="380" alt="locals" src="https://user-images.githubusercontent.com/1232595/112467739-c5f42280-8daa-11eb-8426-7efc3cee5a50.png">

**Comment by johanlajili** [comment] 2021-05-13 15:53
Seeing the same issue on a different (also complex) app.
It's very elusive, hapening once every dozens of refresh on local but more often on a deployed version.
I'd imagine it has something to do with a race condition with lazy components.
I have seen the error on both chrome and firefox.

**Comment by johanlajili** [comment] 2021-05-13 16:27
From very anecdotal evidence, I think this is due to a Suspense directly inside of a Fragment, and might be fixed by this PR https://github.com/preactjs/preact/pull/3072

In the meantime, I've replaced my Fragment with a div and it looks like it fixed it.

**Comment by JoviDeCroock** [comment] 2024-11-01 12:27
Closing since we still have no reproduction here

**Closed by JoviDeCroock** 2024-11-01 12:27 UTC
