### ISSUE TITLE
Preact-router and setState callback does not play nice

### ISSUE THREAD

**Issue by untitledlt** [preactjs/preact#2553] opened 2020-05-25 18:36 UTC
```
"preact": "^10.4.4",
"preact-router": "^3.2.1",
```

### Reproduction
Here is a minimal code to reproduce this issue.
https://codesandbox.io/s/compassionate-rgb-kl85q?file=/src/index.js

I am setting state with `this.setState` and reading it immediately in `setState` callback (second argument). See line # 13

### Steps to reproduce
- open console tab
- find console.log output from line # 14

### Expected Behavior
state should be `{ initial: true, handleRoute: true }`

### Actual Behavior
state is `{ initial: true }`

I can set state and read it immediately in `setState` callback in `componentDidMount` and other places but not in `preact-router`'s onChange callback.

**Comment by marvinhagemeister** [comment] 2020-05-25 20:33
This is a good first issue for anyone to pick up. The solution likely involves setting `component.state` to the correct value just before the callback will be invoked. This likely happens somewhere near `commitRoot()`.

**Comment by jamesb3ll** [comment] 2020-05-27 10:12
Hey @marvinhagemeister, I'm having a look at this and it actually seems the problem is that `preact-router` is calling side-effects in `Router.render`, see [here](https://github.com/preactjs/preact-router/blob/master/src/index.js#L235). If `onChange` function calls `this.setState` it's basically calling `this.setState` in `render`, which is strange 😕
I came up with a simple snippet of the behaviour without `preact-router`:
```js
let log = console.log, i = 0; // value to increment so we don't get infinite loop
class App extends Component {
  state = { initial: true };
  componentDidMount() { this.setState({ didMount: true }, () => log("mounted", this.state)); }
  render() {
    if (i++ == 0) this.setState({ rendered: true }, () => log("callback", this.state));
    log("rendered:", this.state.rendered);
    return String(this.state.rendered);
  }
}
```
In Preact this results in:
```
rendered: undefined
callback { initial: true }
rendered: true
mounted {initial: true, rendered: true, didMount: true}
```

In React:
```
Warning: Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state. 
rendered: undefined
rendered: undefined
rendered: true
rendered: true
callback {initial: true, rendered: true, didMount: true}
mounted {initial: true, rendered: true, didMount: true}
```

I tried adding `c.state = c._nextState` after calling `c.render` here:
https://github.com/preactjs/preact/blob/0f8c55c6cfad8d5cc3aec6785c1f6940998b4782/src/diff/index.js#L173
This leads to the expected behaviour of this PR, `this.state === { initial: true, handleRoute: true }`  in setState callback, but that seems like I'm forcing the next state after render and not the right solution? 😕 If I set `c.state` after render, should we also set `c.props` and context too?

Also, from what I can tell [`commitRoot`](https://github.com/preactjs/preact/blob/0f8c55c6cfad8d5cc3aec6785c1f6940998b4782/src/diff/index.js#L244) calls lifecycle method `componentDidMount` and flushes `setState` callbacks in the same queue. React seems to [`commitLifeCycles`](https://github.com/facebook/react/blob/730ae7afa2a2f620a77490ad4e2fbcc98f326da2/packages/react-reconciler/src/ReactFiberCommitWork.new.js#L516) synchronously and then  [`commitUpdateQueue`](https://github.com/facebook/react/blob/730ae7afa2a2f620a77490ad4e2fbcc98f326da2/packages/react-reconciler/src/ReactFiberCommitWork.new.js#L696) which flushes the `setState` callbacks. I think that's what leads to the callback having the mounted state.

I've been trying to work this out for a few hour now, do you think you could help me out?

P.S. Either I'm really looking in the wrong place or this doesn't look very "beginner-friendly" at all 😛

**Comment by jamesb3ll** [comment] 2020-05-27 12:40
Thanks @JoviDeCroock for replying on [Twitter](https://twitter.com/JoviDeC/status/1265601287460139010) 😃 
From what I understood adding `c.state = c._nextState;` here:
https://github.com/preactjs/preact/blob/0f8c55c6cfad8d5cc3aec6785c1f6940998b4782/src/diff/index.js#L251
This will render the following to the console (with the above code):
```
rendered: true
callback { initial: true, rendered: true, didMount: true }
rendered: true
mounted { initial: true, rendered: true, didMount: true }
```
So I think this fixes the issue 🤦 🎉haha Thanks Jovi!
Although it's still not aligned with React?

**Comment by marvinhagemeister** [comment] 2020-05-27 13:36
Yup, that's perfectly fine 👍

**Comment by developit** [comment] 2020-05-27 15:07
Wow, nice write-up and debugging @jamesb3ll!

One thought I had when thinking about your fix: I wonder if we could achieve the same result by adding that assignment here:
https://github.com/preactjs/preact/blob/0f8c55c6cfad8d5cc3aec6785c1f6940998b4782/src/diff/index.js#L173-L174

```diff
tmp = c.render(c.props, c.state, c.context);
+c.state = c._nextState;
```

**Comment by JoviDeCroock** [comment] 2020-05-27 15:11
@developit wouldn't that be an issue with nested setState callbacks?

```js
setState(x, () => setState)
```

I think the solution of doing in commitRoot is more resilient in that aspect.

**Comment by developit** [comment] 2020-05-27 15:14
@JoviDeCroock `._nextState` is only assigned the first time it gets invalidated, so I assumed this only needs to run once after render invalidates (tbh not sure)

**Comment by jamesb3ll** [comment] 2020-05-27 23:29
Thanks for the replies 😃 

> ```diff
> tmp = c.render(c.props, c.state, c.context);
> +c.state = c._nextState;
> ```

Yeah, this is what I suggested in my first comment:

> I tried adding `c.state = c._nextState` after calling `c.render` here:
https://github.com/preactjs/preact/blob/0f8c55c6cfad8d5cc3aec6785c1f6940998b4782/src/diff/index.js#L173
> 
> This leads to the expected behaviour of this PR:
> `this.state === { initial: true, handleRoute: true }` in setState callback, but that seems like I'm forcing the next state after render and not the right solution? 😕 If I set `c.state` after render, should we also set `c.props` and context too?

Both solutions seem to fix the problem, Option 1:
https://github.com/preactjs/preact/blob/0f8c55c6cfad8d5cc3aec6785c1f6940998b4782/src/diff/index.js#L173
```diff
tmp = c.render(c.props, c.state, c.context);
+c.state = c._nextState;
```
Or Option 2:
https://github.com/preactjs/preact/blob/0f8c55c6cfad8d5cc3aec6785c1f6940998b4782/src/diff/index.js#L251
```diff
c._renderCallbacks = [];
+c.state = c._nextState;
commitQueue.some(cb => {
```

All tests seem to pass on both ✅Nested setStates don't seem to be a problem 🤞 

So, which do you prefer? Or which is better aligned? Option 1 feels like handling an edge case, setting state to new state after render? But with a comment it's possibly more explicit than Option 2? 🤔

**Comment by JoviDeCroock** [comment] 2020-05-29 20:18
Putting it behind render makes the intent clear of being done inside of `render`, so I'm all for it

**Closed** 2020-06-02 12:20 UTC
Labels: beginner-friendly
