### ISSUE TITLE
@react-google-maps/api throwing Cannot read properties of undefined (reading 'current')

### ISSUE THREAD

**Issue by acludo2** [preactjs/preact#3870] opened 2023-01-26 23:34 UTC
- [ ] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
When trying to load a Google Map using the @react-google-maps/api library, the map does not appear and an error is thrown.

**To Reproduce**

```json
{
 "devDependencies": {
    "enzyme": "^3.11.0",
    "enzyme-adapter-preact-pure": "^4.0.0",
    "eslint": "^8.30.0",
    "eslint-config-preact": "^1.3.0",
    "jest": "^27.0.0",
    "jest-preset-preact": "^4.0.5",
    "preact-cli": "^3.4.2",
    "sirv-cli": "^2.0.2"
  },
  "dependencies": {
    "@react-google-maps/api": "^2.17.1",
    "@supabase/supabase-js": "^2.4.1",
    "preact": "^10.11.3",
    "preact-render-to-string": "^5.2.6",
    "preact-router": "^3.2.1",
    "uuid-by-string": "^4.0.0",
    "zustand": "^4.3.2",
    "zustand-persist": "^0.4.0"
  }
}
```
  
```js
import styles from './style.css';
import React from 'react'
import { GoogleMap, useJsApiLoader } from '@react-google-maps/api';

const containerStyle = {
  width: '400px',
  height: '400px'
};

const center = {
  lat: -3.745,
  lng: -38.523
};

function MyComponent() {
  const { isLoaded } = useJsApiLoader({
    id: 'google-map-script',
    googleMapsApiKey: "<API Key>"
  })

  const [map, setMap] = React.useState(null)

  const onLoad = React.useCallback(function callback(map) {
    // This is just an example of getting and using the map instance!!! don't just blindly copy!
    const bounds = new window.google.maps.LatLngBounds(center);
    map.fitBounds(bounds);

    setMap(map)
  }, [])

  const onUnmount = React.useCallback(function callback(map) {
    setMap(null)
  }, [])

  return isLoaded ? (
      <GoogleMap
        mapContainerStyle={containerStyle}
        center={center}
        zoom={10}
        onLoad={onLoad}
        onUnmount={onUnmount}
      >
        { /* Child components, such as markers, info windows, etc. */ }
        <></>
      </GoogleMap>
  ) : <></>
}



const HotdogSection = () => (
  <section className={styles.hotdogSection}>
    <div className={styles.hotdogSectionContent}>
      <div className={styles.hotdogCard}>
        <img src="../../assets/logo.png" alt="Hotdog with ketchup and mustard" className={styles.hotdogCardImg} />
        <div className={styles.hotdogCardInfo}>
          <h2 className={styles.hotdogCardTitle}>La capital del dogo</h2>
          <p className={styles.hotdogCardDescription}>Perros calientes ds carne de res.</p>
        </div>
      </div>
	  </div>
	  <div className={styles.hotdogSectionContent}>
    <MyComponent/>
    </div>
  </section>
);

export default HotdogSection;
```

Here is a sandbox with the error
https://codesandbox.io/s/musing-volhard-386l8o?file=/components/app.js

**Expected behavior**
What should have happened when following the steps above?
@react-google-maps/api should work?

---

**Edited by @rschristian to fix code formatting**

**Comment by rschristian** [comment] 2023-01-27 02:48
It looks like that module is inlining `react-jsx-runtime` (perhaps accidentally) which is not supported. You're essentially mixing React and Preact internals together, doing that. This will need to be corrected upstream, or with [`patch-package`](https://npm.im/patch-package) if you're up to it. Similar issue to #3809

Additionally, it looks like you've accidentally provided your API key in the issue reproduction. You'll need to invalidate that ASAP and generate a new one. Bots constantly crawl GitHub looking for mistakes like this. Your key will be stolen and used by others if you don't do anything.

**Comment by acludo2** [comment] 2023-01-27 13:40
Thanks for the heads up, I could of sworn I left the key out. thanks for the PR for this I was going to resort to patch-package but ill try your PR.

**Comment by rschristian** [comment] 2023-01-27 18:38
I'm going to close this out as there's nothing actionable here. Hopefully this will be corrected upstream soon, it does seem like a genuine mistake.

**Closed** 2023-01-27 18:38 UTC
Labels: upstream

**Comment by rschristian** [comment] 2023-01-30 02:33
Looks like `@react-google-maps/api` v2.18.1 was released, which included my fix. Should be working after an update.
