### ISSUE TITLE
Unnecessary unmounting/mounting children with keys

### ISSUE THREAD

**Issue by yishn** [preactjs/preact#2783] opened 2020-10-03 18:43 UTC
Hi all, I'm the author of [tikzcd-editor](https://github.com/yishn/tikzcd-editor) and am experiencing severe performance degradation after updating Preact recently.

tikzcd-editor is rendering a grid of elements onto the viewport; we only render visible grid cells. The user can use the pan tool to pan the grid, so cells outside of the viewport need to be added while panning, and cells that go outside of the viewport get removed. 

Each grid cell will be typeset using MathJax on every change, which is expensive, that's why every grid cell has a `key` set to its coordinates, so we avoid rerendering while panning. This worked fine in v10.4.1, but in v10.4.2 and the latest version v10.5.3, we experience a lot of unnecessary rerenders.

# Reproduction

### Steps to reproduce

Here's a [deployment of tikzcd-editor with v10.5.3 with a sample diagram](https://yichuanshen.de/applications/tikzcd-test/#N4Igdg9gJgpgziAXAbVABwnAlgFyxMJZABgBpiBdUkANwEMAbAVxiRAEEAdTvAW3gAEAIRABfUuky58hFACZyVWoxZsAwtz6CAImIkgM2PASIKAjEvrNWiEGKUwoAc3hFQAMwBOEXkjIgcCCQzaitVW3duAGMsTyiBJz0Pb19EEICgxDlRClEgA). When trying to pan the viewport, you can see it's not smooth at all. When opening the Devtools you can see that Preact is unnecessarily unmounting/mounting elements.

### Expected Behavior

Visible children should not be unmounted/remounted like in v10.4.1:

![Good behavior](https://user-images.githubusercontent.com/9217349/94998927-e7234580-05b5-11eb-8e90-08cc1f441c03.gif)

### Actual Behavior

A lot of unnecessary unmounting/rendering of children as experienced in v10.4.2 and v10.5.3:

![Bad behavior](https://user-images.githubusercontent.com/9217349/94998938-01f5ba00-05b6-11eb-8ef8-7738a5e0fa3d.gif)

**Comment by marvinhagemeister** [comment] 2020-10-03 20:08
Probably related to #2619

**Comment by darsain** [comment] 2020-11-06 19:55
Was told my issues is related, so here is my case report:

Whenever you remove an uncertain number of elements from a keyed list, the elements after them get remounted. The number seems to differ between environments. On my local app it's 20+, on the isolated example below it's 50+.

Here is a visualization of the issue. Elements that get remounted flash red. The last 20 items should never flash, as only range 20-80 is being toggled:

![xG61GfMSA5](https://user-images.githubusercontent.com/538801/98408271-2f2fff00-2071-11eb-86c5-7265844452e6.gif)

This doesn't happen for smaller amount of items being toggled:

![VVaLqUrt3k](https://user-images.githubusercontent.com/538801/98408298-3a832a80-2071-11eb-84b9-7039204683ab.gif)

The issue is isolated here: https://codesandbox.io/s/cocky-joliot-9gw5v

**Comment by pavulon** [comment] 2020-11-16 23:31
In your case @darsain, the magic number is more than a half. Probably [this](https://github.com/preactjs/preact/blob/master/src/diff/children.js#L284) has something to do with it.

**Comment by developit** [comment] 2020-11-23 14:55
Echoing from various discussions elsewhere: the `j/2` child search optimization was never supposed to apply to keyed matches, which to me makes this a bug rather than just a performance degradation.

**Comment by cpatti97100** [comment] 2021-05-04 18:30
good evening all :) is there undergoing work about this? thanks!

**Comment by jaydenseric** [comment] 2021-12-13 08:45
This issue causes serious FOUC problems when rendering arrays of `link` DOM nodes for stylesheets and something early in the list changes, see:

https://github.com/preactjs/preact/issues/3285#issuecomment-992227947

What is an ETA for a fix? Is it fixed in `main` branch already? Will it ship in Preact v11, or in a v10 patch? If there is a prerelease version with the fix, is there a way to use it via [JSPM CDN](https://jspm.org/docs/cdn)? Are there any known workarounds?

**Comment by JoviDeCroock** [comment] 2021-12-13 11:35
@jaydenseric this has been fixed in v11, introducing this fix in v10 would be a huge perf impediment I've tried in https://github.com/preactjs/preact/pull/3359 for v11 with our new diffing algo it is a net positive https://github.com/preactjs/preact/pull/3358

**Comment by jaydenseric** [comment] 2021-12-14 00:14
That's great news, when do you think v11 will be released? I'm currently working full time on a buildless SSR web app framework for Deno based around Preact, and this issue is a blocker. If there is no way to try a v11 prerelease, and a stable v11 if far away, I might have to reschedule my next few weeks.

Also, I'm keen to contribute to improving Preact, particularly regarding Deno compatibility. Is the `main` branch the one to PR?

**Closed** 2023-06-14 09:14 UTC
Labels: 11.x
