### ISSUE TITLE
Problem extending DOMAttributes type with new typescript typings.

### ISSUE THREAD

**Issue by mseddon** [preactjs/preact#1544] opened 2019-04-17 14:14 UTC
I used to be able to attach new attribute types to preact by doing something like:

```typescript
declare namespace JSX {
	interface DOMAttributes {
		onSwipeStart?: (e: any) => void;
		onSwipeEnd?: (e: any) => void;
		onSwipeMove?: (e: any) => void;
	}
}
```

Since #1448, `JSX` has gone, but attempting:
```typescript
declare namespace preact.JSX {
	interface DOMAttributes {
		onSwipeStart?: (e: any) => void;
		onSwipeEnd?: (e: any) => void;
		onSwipeMove?: (e: any) => void;
	}
}
```

causes every jsx element to type error with:

`{ children: Element[] } has no properties in common with 'HTMLAttributes'`.

What is the correct way to add new events like this since the change? Thanks!

**Comment by maxpatiiuk** [comment] 2024-06-03 01:06
This solved it for me:
https://github.com/preactjs/preact/issues/1180#issuecomment-643681851

**Comment by marvinhagemeister** [comment] 2024-06-03 06:58
Closing as duplicate of https://github.com/preactjs/preact/issues/1180

**Closed by marvinhagemeister** 2024-06-03 06:58 UTC
