### ISSUE TITLE
React Router v4 doesn't work properly with Preact X

### ISSUE THREAD

**Issue by VintorezVS** [preactjs/preact#3284] opened 2021-10-19 13:22 UTC
- [x] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
React Router v4.x.x doesn't work properly with Preact X latest version (v10.5.15) but works with Preact v8.x.x version.

**To Reproduce**
Minimal example: https://codesandbox.io/s/confident-ives-j9by2?file=/src/index.js

1. Go to https://codesandbox.io/s/confident-ives-j9by2?file=/src/index.js
2. Click on link 'To First' or 'To Second'
3. Routing doesn't work. Related components are not rendered

**Expected behavior**
Routing should work properly. 'First' component should be rendered after clicking on the 'To First' link and 'Second' component should be rendered after clicking on the 'To Second' link.

**Comment by VintorezVS** [comment] 2021-11-02 12:48
Could anyone look in here?

**Comment by developit** [comment] 2021-11-02 21:27
Hi @VintorezVS - sorry for the delay. I spent some time stepping through your example, and I haven't yet been able to figure out the issue. My theory is that this relates to VNode equality bailout, which is an optimization that was not present in Preact 8.

So far all I have determined is that this broke in Preact 10.4.0 - 10.3.4 works correctly in your demo.

**Comment by developit** [comment] 2021-11-03 14:48
@VintorezVS Alright, so @JoviDeCroock found the issue! React Router v4 and v5 are API-compatible, and everyone is recommended to upgrade to v5. There is a bug in React Router v4 caused by failure to use `cloneElement()` when returning identical trees (in [Router](https://github.com/remix-run/react-router/blob/eef79d529efb037d84d99efdedef2baa0941c8c1/packages/react-router/modules/Route.js#L63) and [Route](https://github.com/remix-run/react-router/blob/eef79d529efb037d84d99efdedef2baa0941c8c1/packages/react-router/modules/Router.js#L56)), and that bug was fixed in v5.

Your sandbox works when updated to RR5: https://codesandbox.io/s/bold-sutherland-nis8n?file=/src/index.js

**Comment by VintorezVS** [comment] 2021-11-10 11:12
@developit Thank you for investigation. The workaround works well.

**Closed** 2021-11-13 10:19 UTC
Labels: bug, compat, workaround
